# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for LibreChat tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python librechat_mcp_mock.py

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
from __future__ import annotations

# --- catalog.py ---
"""Pure-Python mock data used by the FastMCP server and unit tests.

A valid call that matches nothing returns an empty list. That is not an error.
Protocol problems (unknown tool, invalid arguments, timeout) are errors.
"""


from typing import Any

AVAILABLE_TOOLS = (
    "find_municipalities",
    "find_transaction_prices",
    "find_stations",
)

TOOL_DESCRIPTIONS = {
    "find_municipalities": "Find mock municipalities by name or prefecture.",
    "find_transaction_prices": "Return mock property transaction prices. This never calls a live API.",
    "find_stations": "Find mock stations in a municipality.",
}

MUNICIPALITIES = (
    {"code": "13101", "name": "Chiyoda", "prefecture": "Tokyo"},
    {"code": "14109", "name": "Yokohama", "prefecture": "Kanagawa"},
    {"code": "12207", "name": "Matsudo", "prefecture": "Chiba"},
)

STATIONS = {
    "14109": [{"name": "Yokohama", "line": "JR"}],
    "12207": [{"name": "Matsudo", "line": "JR Joban"}],
    "13101": [{"name": "Tokyo", "line": "JR"}],
}

KNOWN_MUNICIPALITY_CODES = tuple(row["code"] for row in MUNICIPALITIES)


def search_municipalities(query: str) -> list[dict[str, str]]:
    """Return deterministic municipality-like records; no external API is called."""
    normalized = query.strip().lower()
    if not normalized:
        return []
    return [
        row
        for row in MUNICIPALITIES
        if normalized in row["name"].lower() or normalized in row["prefecture"].lower()
    ]


def search_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
    """Return a stable fake transaction-price result, or [] when the code is unknown."""
    if municipality_code not in KNOWN_MUNICIPALITY_CODES:
        return []
    return [
        {
            "municipality_code": municipality_code,
            "year": year,
            "price_yen": 52_000_000,
            "property_type": "condominium",
            "source": "mock",
        }
    ]


def search_stations(municipality_code: str) -> list[dict[str, str]]:
    """Return deterministic station-like records, or [] when the code is unknown."""
    return list(STATIONS.get(municipality_code, []))


def dispatch_tool(name: str, arguments: dict[str, Any]) -> list[dict[str, Any]]:
    """In-process tool body. FastMCP wrappers and the stub front share this."""
    if name == "find_municipalities":
        return search_municipalities(str(arguments.get("query", "")))
    if name == "find_stations":
        return search_stations(str(arguments.get("municipality_code", "")))
    if name == "find_transaction_prices":
        return search_transaction_prices(
            str(arguments.get("municipality_code", "")),
            int(arguments.get("year", 2025)),
        )
    raise KeyError(name)

# --- record.py ---
"""JSONL call log shared by the package server and the generated standalone file."""


import json
import os
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Callable

OUTCOME_SUCCESS = "success"
OUTCOME_EMPTY = "empty"
OUTCOME_ERROR = "error"

EVENT_TOOLS_CALL = "tools/call"

# Real chat UIs rarely put lab chat_id in MCP `_meta`. They *can* forward a
# conversation id on the HTTP hop; we also mint one per MCP session so a
# tools/call is never an orphan row.
CHAT_ID_HEADER_KEYS = (
    "x-chat-id",
    "x-lab-chat-id",
    "x-conversation-id",
    "x-owui-chat-id",
    "x-openwebui-chat-id",  # OWUI ENABLE_FORWARD_USER_INFO_HEADERS
)

MESSAGE_ID_HEADER_KEYS = (
    "x-openwebui-message-id",
    "x-message-id",
)


def new_chat_id() -> str:
    """Lab conversation pin. INLINE so the standalone mock can mint one too."""
    return f"chat_{uuid.uuid4().hex[:24]}"


def new_call_id() -> str:
    """OpenAI ``tool_calls[].id`` shape. One mint, used by chat_sim and the stub."""
    return f"call_{uuid.uuid4().hex[:24]}"


def _id_from_headers(headers: dict[str, str] | None, keys: tuple[str, ...]) -> str | None:
    if not headers:
        return None
    lowered = {str(key).lower(): str(value).strip() for key, value in headers.items()}
    for key in keys:
        value = lowered.get(key)
        if value:
            return value
    return None


def chat_id_from_headers(headers: dict[str, str] | None) -> str | None:
    return _id_from_headers(headers, CHAT_ID_HEADER_KEYS)


def resolve_correlation(
    *,
    meta: dict[str, Any] | None,
    headers: dict[str, str] | None = None,
    session_id: str | None = None,
    session_chats: dict[str, str] | None = None,
    mint: Callable[[], str] | None = None,
) -> dict[str, Any]:
    """Resolve a chat_id without rewriting the caller's `_meta`.

    Priority: ``meta.chat_id`` → well-known headers → this MCP session's
    previously minted id → mint a new ``chat_*`` and remember it for the session.
    """
    meta = dict(meta or {})
    minted = mint or new_chat_id
    if meta.get("chat_id"):
        chat_id = str(meta["chat_id"])
        source = "meta"
    else:
        header_id = chat_id_from_headers(headers)
        if header_id:
            chat_id = header_id
            source = "header"
        elif session_id and session_chats is not None and session_id in session_chats:
            chat_id = session_chats[session_id]
            source = "session"
        else:
            chat_id = minted()
            source = "minted"

    if session_id and session_chats is not None:
        session_chats.setdefault(session_id, chat_id)

    debug: dict[str, Any] = {
        "chat_id": chat_id,
        "chat_id_source": source,
    }
    if session_id:
        debug["session_id"] = session_id
    message_id = _id_from_headers(headers, MESSAGE_ID_HEADER_KEYS)
    if message_id:
        debug["message_id"] = message_id
    if meta.get("call_id") is not None:
        debug["call_id"] = meta["call_id"]
        debug["call_id_source"] = "meta"
    else:
        debug["call_id"] = new_call_id()
        debug["call_id_source"] = "minted"
    if meta.get("trace_id") is not None:
        debug["trace_id"] = meta["trace_id"]
    if meta.get("source") is not None:
        debug["source"] = meta["source"]
    return debug


def record_call(
    *,
    tool: str,
    arguments: dict[str, Any],
    outcome: str,
    result: Any = None,
    error: str | None = None,
    meta: dict[str, Any] | None = None,
    debug: dict[str, Any] | None = None,
    duration_ms: float | None = None,
    event: str = EVENT_TOOLS_CALL,
) -> None:
    """Append one call record when MCP_TOOLCALL_LOG is set.

    `arguments` are the values received on `tools/call` before pydantic coercion.
    `outcome` is success, empty (valid call, no rows), or error.

    `meta` is whatever the caller put in the request's MCP `_meta` field (e.g.
    a chat-simulated caller's `call_id`/`chat_id`, or a caller talking to MCP
    directly passing its own correlation id). It is opaque to this function —
    logged verbatim when present — so a trace can be reconstructed from this
    JSONL file regardless of which path (chat-simulated or direct) made the
    call.

    `debug` is server-side correlation (resolved chat_id, source, session,
    result_n). It is *not* merged into `meta`, so existing exact-meta tests
    and callers keep a clean wire object.
    """
    log_path = os.environ.get("MCP_TOOLCALL_LOG")
    if not log_path:
        return
    row: dict[str, Any] = {
        "at": datetime.now(UTC).isoformat(),
        "event": event,
        "tool": tool,
        "arguments": arguments,
        "outcome": outcome,
    }
    if duration_ms is not None:
        row["duration_ms"] = duration_ms
    if meta:
        row["meta"] = meta
    debug_row = dict(debug) if debug else {}
    if outcome == OUTCOME_ERROR:
        row["error"] = error or "unknown error"
    else:
        row["result"] = result
        if isinstance(result, list):
            debug_row["result_n"] = len(result)
    if debug_row:
        row["debug"] = debug_row
        if debug_row.get("chat_id"):
            row["chat_id"] = debug_row["chat_id"]
    path = Path(log_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as log_file:
        log_file.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    """Read a JSONL file; skip blank or broken lines (debug logs are append-only)."""
    if not path.is_file():
        return []
    events: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return events

# --- server.py ---
"""FastMCP server exposing a small, deterministic real-estate-style mock API."""


import asyncio
import os
import time
from typing import Any

from fastmcp import FastMCP
from fastmcp.server.middleware import Middleware, MiddlewareContext



def _tool_delay_seconds() -> float:
    raw = os.environ.get("MCP_TOOL_DELAY_SECONDS", "0")
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 0.0


def _result_payload(result: Any) -> Any:
    structured = getattr(result, "structured_content", None)
    if isinstance(structured, dict) and "result" in structured:
        return structured["result"]
    if structured is not None:
        return structured
    content = getattr(result, "content", None)
    if not content:
        return []
    texts = [getattr(item, "text", None) for item in content]
    return texts[0] if len(texts) == 1 else texts


def _outcome_for_result(result: Any, payload: Any) -> str:
    if getattr(result, "is_error", False):
        return OUTCOME_ERROR
    if payload == [] or payload == {}:
        return OUTCOME_EMPTY
    return OUTCOME_SUCCESS


def _request_meta(context: MiddlewareContext) -> dict[str, Any]:
    """Pull the caller-supplied MCP `_meta` object off a tools/call request.

    Any client can attach arbitrary correlation data here (a chat-simulated
    caller's `call_id`/`chat_id`, or a direct caller's own trace id) — MCP
    reserves `_meta` exactly for this, so no protocol extension is needed.

    Note: `context.message.meta` is *not* the original request's `_meta` —
    FastMCP's own tools/call dispatch (fastmcp==3.4.7) rebuilds
    CallToolRequestParams internally and overwrites `_meta` with its own
    version-pinning metadata before middleware ever sees it. The original,
    client-supplied `_meta` survives on the lower-level request context
    instead, so that is what we read here.
    """
    ctx = context.fastmcp_context
    request_context = ctx.request_context if ctx is not None else None
    meta = getattr(request_context, "meta", None) if request_context is not None else None
    if meta is None:
        return {}
    if hasattr(meta, "model_dump"):
        meta = meta.model_dump(mode="json", exclude_none=True)
    return {k: v for k, v in dict(meta).items() if k != "progressToken"}


def _http_headers() -> dict[str, str]:
    """Best-effort request headers. Empty when this is not an HTTP hop."""
    try:
        from fastmcp.server.dependencies import get_http_headers
    except Exception:
        return {}
    try:
        return dict(get_http_headers() or {})
    except Exception:
        return {}


def _session_id(context: MiddlewareContext) -> str | None:
    ctx = context.fastmcp_context
    if ctx is None:
        return None
    try:
        return str(ctx.session_id)
    except Exception:
        return None


class ObservabilityMiddleware(Middleware):
    """Log every tools/call, including unknown names and validation failures.

    Also resolves a ``chat_id`` for debugging: caller `_meta`, then
    ``X-Chat-Id`` / ``X-Conversation-Id`` headers, then the id minted for
    this MCP session on the first call.
    """

    def __init__(self) -> None:
        super().__init__()
        self._session_chats: dict[str, str] = {}

    def _debug(self, context: MiddlewareContext, meta: dict[str, Any]) -> dict[str, Any]:
        return resolve_correlation(
            meta=meta,
            headers=_http_headers(),
            session_id=_session_id(context),
            session_chats=self._session_chats,
        )

    async def on_call_tool(self, context: MiddlewareContext, call_next):
        delay = _tool_delay_seconds()
        name = context.message.name
        arguments = dict(context.message.arguments or {})
        meta = _request_meta(context)
        debug = self._debug(context, meta)
        started = time.perf_counter()
        if delay:
            await asyncio.sleep(delay)
        try:
            result = await call_next(context)
        except Exception as exc:
            self._emit(name, arguments, meta, debug, started, outcome=OUTCOME_ERROR, error=str(exc))
            raise
        payload = _result_payload(result)
        outcome = _outcome_for_result(result, payload)
        if outcome == OUTCOME_ERROR:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, error=str(payload))
        else:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, result=payload)
        return result

    @staticmethod
    def _emit(
        name: str,
        arguments: dict[str, Any],
        meta: dict[str, Any],
        debug: dict[str, Any],
        started: float,
        *,
        outcome: str,
        result: Any = None,
        error: str | None = None,
    ) -> None:
        record_call(
            tool=name,
            arguments=arguments,
            outcome=outcome,
            result=result,
            error=error,
            meta=meta,
            debug=debug,
            duration_ms=round((time.perf_counter() - started) * 1000, 3),
        )


def create_mcp() -> FastMCP:
    """Build the Streamable HTTP mock server used by tests and Open WebUI."""
    mcp = FastMCP("mcp-toolcall-lab")
    mcp.add_middleware(ObservabilityMiddleware())

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_municipalities"])
    def find_municipalities(query: str) -> list[dict[str, str]]:
        return dispatch_tool("find_municipalities", {"query": query})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_transaction_prices"])
    def find_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
        return dispatch_tool("find_transaction_prices", {"municipality_code": municipality_code, "year": year})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_stations"])
    def find_stations(municipality_code: str) -> list[dict[str, str]]:
        return dispatch_tool("find_stations", {"municipality_code": municipality_code})

    return mcp


def run_server(mcp: FastMCP | None = None) -> None:
    server = mcp or create_mcp()
    server.run(
        transport="http",
        host=os.environ.get("MCP_HOST", "127.0.0.1"),
        port=int(os.environ.get("MCP_PORT", "8000")),
        path="/mcp",
    )


mcp = create_mcp()


if __name__ == "__main__":
    run_server(mcp)
