# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for Open WebUI tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python openwebui_mcp_mock.py

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
from __future__ import annotations

# --- mock/common.py ---
"""Stdlib bits both lab mocks can import without taking on each other's protocol.

Used by the MCP server (via ``record``) and the OpenAI-compatible demo.
No FastMCP, no OpenAI ``tool_calls`` decision, no MCP ``_meta`` schema —
those stay in the mock that owns that wire.
"""


import json
import uuid
from pathlib import Path
from typing import Any

CHAT_ID_HEADER_KEYS = (
    "x-chat-id",
    "x-lab-chat-id",
    "x-conversation-id",
    "x-owui-chat-id",
    "x-openwebui-chat-id",  # OWUI ENABLE_FORWARD_USER_INFO_HEADERS
)

MESSAGE_ID_HEADER_KEYS = (
    "x-openwebui-message-id",
    "x-message-id",
)


def new_chat_id() -> str:
    """Lab conversation pin. Not LibreChat's conversationId or OWUI chat.id."""
    return f"chat_{uuid.uuid4().hex[:24]}"


def new_call_id() -> str:
    """OpenAI ``tool_calls[].id`` shape. Same mint for MCP debug and the OpenAI mock."""
    return f"call_{uuid.uuid4().hex[:24]}"


def id_from_headers(headers: Any, keys: tuple[str, ...]) -> str | None:
    """Return the first non-empty value among ``keys`` (case-insensitive)."""
    if not headers:
        return None
    items = headers.items() if hasattr(headers, "items") else []
    lowered = {str(key).lower(): str(value).strip() for key, value in items}
    for key in keys:
        value = lowered.get(key)
        if value:
            return value
    return None


def chat_id_from_headers(headers: Any) -> str | None:
    return id_from_headers(headers, CHAT_ID_HEADER_KEYS)


def append_jsonl(path: str | Path, row: dict[str, Any]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    """Read a JSONL file; skip blank or broken lines (debug logs are append-only)."""
    target = Path(path)
    if not target.is_file():
        return []
    events: list[dict[str, Any]] = []
    for line in target.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return events


def close_http11_sse(handler: Any) -> None:
    """End an HTTP/1.1 SSE response. Keep-alive with no length hangs the next request.

    Same class of bug as markdown ``demos/openai_compat_mock.py`` (c0dcd15).
    JSON responses that already send ``Content-Length`` do not need this.
    """
    handler.send_header("Connection", "close")
    handler.close_connection = True

# --- markdown_lib.py ---
"""Load the vendored stdlib ``markdown.py`` without making it a package import.

The sibling repo ships one file. We keep a snapshot under ``vendor/`` so
Docker / GitHub Pages builds stay offline after checkout. If the file is
missing, callers fall back to the stub's own ATX splitter.

``Section``/``slugify``/``parse_sections``/``lookup_heading`` live here
too: the heading -> body split is "use the vendored module, else a local
ATX regex fallback" regardless of *what* corpus is being split (a
fixtures/stub_front/*.md file for stub_front.py, or a live Wikipedia
extract converted to ATX for wikipedia_tool.py) -- one implementation,
not one per caller.
"""


import hashlib
import importlib.util
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[2]
PROVENANCE_PATH = REPO_ROOT / "vendor" / "markdown.provenance.json"

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")


@dataclass(frozen=True)
class Section:
    level: int
    title: str
    slug: str
    body: str
    line: int


def slugify(title: str) -> str:
    lowered = title.casefold().strip()
    return re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")


def parse_sections(markdown: str) -> list[Section]:
    """Heading → body. Prefer vendored ``markdown.py``; ATX regex is the fallback."""
    md = load_markdown()
    if md is not None and hasattr(md, "split_sections"):
        sections: list[Section] = []
        line = 1
        for part in md.split_sections(markdown):
            level = int(part.get("level") or 0)
            title = str(part.get("title") or "")
            raw = str(part.get("content") or "")
            if level <= 0 or not title:
                line += raw.count("\n") or 1
                continue
            body_lines = raw.splitlines()
            body = "\n".join(body_lines[1:]).strip()
            sections.append(Section(level, title, slugify(title), body, line))
            line += raw.count("\n") or 1
        return sections
    lines = markdown.splitlines()
    found: list[tuple[int, int, str]] = []
    for index, line in enumerate(lines):
        match = _HEADING_RE.match(line)
        if match:
            found.append((index, len(match.group(1)), match.group(2).strip()))
    sections = []
    for idx, (start, level, title) in enumerate(found):
        end = found[idx + 1][0] if idx + 1 < len(found) else len(lines)
        body = "\n".join(lines[start + 1 : end]).strip()
        sections.append(Section(level, title, slugify(title), body, start + 1))
    return sections


def lookup_heading(query: str, sections: list[Section], *, fuzzy: bool = True) -> Section | None:
    needle = query.strip()
    if needle.startswith("#"):
        needle = needle.lstrip("#").strip()
    if not needle:
        return None
    slug = slugify(needle)
    folded = needle.casefold()
    for section in sections:
        if section.title == needle or section.title.casefold() == folded or section.slug == slug:
            return section
    if not fuzzy:
        return None
    for section in sections:
        title = section.title.casefold()
        if title.startswith(folded) or folded.startswith(title) or folded in title:
            return section
    return None


def markdown_py_path() -> Path | None:
    override = os.environ.get("MARKDOWN_PY")
    candidates = []
    if override:
        candidates.append(Path(override))
    candidates.append(REPO_ROOT / "vendor" / "markdown.py")
    candidates.append(Path("/app/vendor/markdown.py"))
    for path in candidates:
        if path.is_file():
            return path
    return None


def load_markdown() -> ModuleType | None:
    path = markdown_py_path()
    if path is None:
        return None
    spec = importlib.util.spec_from_file_location("lab_vendored_markdown", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def load_provenance() -> dict[str, str]:
    return json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))


def assert_markdown_provenance(path: Path | None = None) -> dict[str, str]:
    """Fail if the vendored file drifted from the recorded commit/blob."""
    recorded = load_provenance()
    target = path or markdown_py_path()
    if target is None:
        raise FileNotFoundError("vendor/markdown.py is missing")
    digest = hashlib.sha256(target.read_bytes()).hexdigest()
    blob = git_blob_sha(target)
    if blob != recorded["blob_sha"] or digest != recorded["sha256"]:
        raise ValueError(
            f"vendored markdown.py does not match {PROVENANCE_PATH.name}: "
            f"blob={blob} sha256={digest} recorded={recorded}"
        )
    return recorded

# --- wikipedia_tool.py ---
"""Fetch a real Wikipedia article's sections over HTTP.

This is the one tool in this lab's MCP catalog that is **not** a
deterministic offline mock -- every other tool in ``catalog.py`` returns
canned data on purpose (see its own module docstring: "never calls a
live API"). This one calls Wikipedia's own action API for real, so a
heading-pulldown + section-extraction UX can be tried against a genuine
article, not only the vendored ``fixtures/stub_front/*.md`` corpus.

Wikipedia's ``action=query&prop=extracts&explaintext=1&exsectionformat=wiki``
does the heavy lifting: it returns already-plain-text article content
(infoboxes, references, navboxes, and other markup already stripped by
Wikipedia's own extract engine) with MediaWiki ``== Heading ==`` markers.
No HTML or wikitext parsing happens here -- those markers are rewritten
to ATX (``## Heading``) and handed to
``mcp_toolcall_lab.markdown_lib.parse_sections()``, the same
heading-splitter every other corpus in this repo already goes through.
One implementation, not a second one for "real" documents.

This sandbox's own dev environment cannot reach en.wikipedia.org (the
agent proxy denies the CONNECT, same as huggingface.co -- see
scripts/fetch_tiny_cpu_gguf.py's module docstring for that precedent),
so the live path is covered by unit tests against a mocked
``urllib.request.urlopen`` here, plus one real-network integration test
gated behind ``MCP_TOOLCALL_LAB_LIVE_WIKIPEDIA=1`` for a human or a
CI runner with real internet to opt into -- never on by default, so a
plain ``pytest -q`` never depends on Wikipedia being reachable.
"""


import json
import re
import urllib.error
import urllib.parse
import urllib.request
from typing import Any


WIKIPEDIA_API = "https://{lang}.wikipedia.org/w/api.php"
DEFAULT_LANG = "en"
TIMEOUT = 10.0
USER_AGENT = "mcp-toolcall-lab/1.0 (https://github.com/myon-bioinformatics/mcp-toolcall-lab; lab demo, not production traffic)"

_WIKI_HEADING_RE = re.compile(r"^(=+)\s*(.+?)\s*=+\s*$", re.MULTILINE)


class WikipediaFetchError(RuntimeError):
    """The live fetch failed: network, timeout, no such article, or a bad response."""


def _wiki_headings_to_atx(text: str) -> str:
    """MediaWiki ``== Heading ==`` -> ATX ``## Heading``.

    Wikipedia's plaintext extract never emits a single ``=`` (that would be
    the article's own title, which is not part of the extract body), so
    level 2 is the shallowest marker actually seen; it is kept as ATX
    level 2 to match fixtures/stub_front/wiki_yokohama.md's own shape,
    where the fetched article's title is a separately-added level-1 ATX
    heading wrapping the lead paragraph and every ``==`` section under it.
    """

    def replace(match: re.Match[str]) -> str:
        level = len(match.group(1))
        return f"{'#' * level} {match.group(2)}"

    return _WIKI_HEADING_RE.sub(replace, text)


def _fetch_extract(title: str, lang: str) -> tuple[str, str]:
    """Return (canonical_title, plaintext_extract_with_wiki_headings)."""
    query = urllib.parse.urlencode(
        {
            "action": "query",
            "format": "json",
            "prop": "extracts",
            "explaintext": 1,
            "exsectionformat": "wiki",
            "redirects": 1,
            "titles": title,
        }
    )
    url = f"{WIKIPEDIA_API.format(lang=lang)}?{query}"
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise WikipediaFetchError(f"could not fetch {title!r} from {lang}.wikipedia.org: {exc}") from exc

    pages = (payload.get("query") or {}).get("pages") or {}
    page = next(iter(pages.values()), None)
    if not isinstance(page, dict) or "missing" in page:
        raise WikipediaFetchError(f"no {lang}.wikipedia.org article named {title!r}")
    extract = str(page.get("extract") or "")
    canonical_title = str(page.get("title") or title)
    return canonical_title, extract


def fetch_article_sections(title: str, *, lang: str = DEFAULT_LANG) -> list[Section]:
    """Sections for a real Wikipedia article, via the same ``Section``
    shape (and the same ``parse_sections()``) as every other corpus in
    this repo -- so ``lookup_heading()`` works identically on either."""
    canonical_title, extract = _fetch_extract(title, lang)
    atx = f"# {canonical_title}\n\n{_wiki_headings_to_atx(extract)}"
    return parse_sections(atx)


def fetch_wikipedia_section(title: str, heading: str = "", *, lang: str = DEFAULT_LANG) -> list[dict[str, Any]]:
    """MCP tool body: ``dispatch_tool("fetch_wikipedia_section", ...)``.

    No ``heading`` (or a blank one): return every section's title only --
    the "pulldown" list, deliberately without body text so a caller lists
    options before committing to a possibly-large fetch's body payload.
    A ``heading`` that matches (see ``lookup_heading()`` -- exact first,
    then fuzzy): that one section's title + body. A ``heading`` that
    matches nothing is a normal empty result, not an error -- same
    "valid call, no rows" contract catalog.py's other tools use. A fetch
    that fails outright (network, no such article) raises
    ``WikipediaFetchError``, which the caller lets propagate as an actual
    MCP tool error, same as any other unexpected exception in this catalog.
    """
    sections = fetch_article_sections(title, lang=lang)
    if not heading.strip():
        return [{"heading": section.title} for section in sections]
    match = lookup_heading(heading, sections, fuzzy=True)
    if match is None:
        return []
    return [{"heading": match.title, "body": match.body}]

# --- catalog.py ---
"""Pure-Python mock data used by the FastMCP server and unit tests.

A valid call that matches nothing returns an empty list. That is not an error.
Protocol problems (unknown tool, invalid arguments, timeout) are errors.

``fetch_wikipedia_section`` is the one tool below that is NOT a
deterministic offline mock -- it is registered here (same
``AVAILABLE_TOOLS``/``TOOL_DESCRIPTIONS``/``dispatch_tool()`` surface as
every other tool, so it is callable the same way over real MCP) but its
actual implementation, including the "this makes a real HTTP call" fact,
lives in ``wikipedia_tool.py``, not here -- see that module's docstring.
"""


from typing import Any


AVAILABLE_TOOLS = (
    "find_municipalities",
    "find_transaction_prices",
    "find_stations",
    "fetch_wikipedia_section",
)

TOOL_DESCRIPTIONS = {
    "find_municipalities": "Find mock municipalities by name or prefecture.",
    "find_transaction_prices": "Return mock property transaction prices. This never calls a live API.",
    "find_stations": "Find mock stations in a municipality.",
    "fetch_wikipedia_section": (
        "Fetch a real Wikipedia article's sections over HTTP (the one tool here that is not a "
        "mock). Omit `heading` to list section titles (a pulldown); pass one to get that "
        "section's body. Unmatched heading is an empty result, not an error."
    ),
}

MUNICIPALITIES = (
    {"code": "13101", "name": "Chiyoda", "prefecture": "Tokyo"},
    {"code": "14109", "name": "Yokohama", "prefecture": "Kanagawa"},
    {"code": "12207", "name": "Matsudo", "prefecture": "Chiba"},
)

STATIONS = {
    "14109": [{"name": "Yokohama", "line": "JR"}],
    "12207": [{"name": "Matsudo", "line": "JR Joban"}],
    "13101": [{"name": "Tokyo", "line": "JR"}],
}

KNOWN_MUNICIPALITY_CODES = tuple(row["code"] for row in MUNICIPALITIES)


def search_municipalities(query: str) -> list[dict[str, str]]:
    """Return deterministic municipality-like records; no external API is called."""
    normalized = query.strip().lower()
    if not normalized:
        return []
    return [
        row
        for row in MUNICIPALITIES
        if normalized in row["name"].lower() or normalized in row["prefecture"].lower()
    ]


def search_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
    """Return a stable fake transaction-price result, or [] when the code is unknown."""
    if municipality_code not in KNOWN_MUNICIPALITY_CODES:
        return []
    return [
        {
            "municipality_code": municipality_code,
            "year": year,
            "price_yen": 52_000_000,
            "property_type": "condominium",
            "source": "mock",
        }
    ]


def search_stations(municipality_code: str) -> list[dict[str, str]]:
    """Return deterministic station-like records, or [] when the code is unknown."""
    return list(STATIONS.get(municipality_code, []))


def dispatch_tool(name: str, arguments: dict[str, Any]) -> list[dict[str, Any]]:
    """In-process tool body. FastMCP wrappers and the stub front share this."""
    if name == "find_municipalities":
        return search_municipalities(str(arguments.get("query", "")))
    if name == "find_stations":
        return search_stations(str(arguments.get("municipality_code", "")))
    if name == "find_transaction_prices":
        return search_transaction_prices(
            str(arguments.get("municipality_code", "")),
            int(arguments.get("year", 2025)),
        )
    if name == "fetch_wikipedia_section":
        return fetch_wikipedia_section(
            str(arguments.get("title", "")),
            str(arguments.get("heading", "")),
        )
    raise KeyError(name)

# --- record.py ---
"""JSONL call log shared by the package server and the generated standalone file.

Id mints, header lookup, and the JSONL writer live in ``mock.common`` so the
OpenAI demo can use the same helpers without importing this MCP log schema.
"""


import os
from datetime import UTC, datetime
from typing import Any, Callable


OUTCOME_SUCCESS = "success"
OUTCOME_EMPTY = "empty"
OUTCOME_ERROR = "error"

EVENT_TOOLS_CALL = "tools/call"

__all__ = [
    "CHAT_ID_HEADER_KEYS",
    "EVENT_TOOLS_CALL",
    "MESSAGE_ID_HEADER_KEYS",
    "OUTCOME_EMPTY",
    "OUTCOME_ERROR",
    "OUTCOME_SUCCESS",
    "chat_id_from_headers",
    "new_call_id",
    "new_chat_id",
    "read_jsonl",
    "record_call",
    "resolve_correlation",
    "usable_session_id",
]


def usable_session_id(session_id: object | None) -> str | None:
    """Keep a missing MCP session missing. ``str(None)`` is ``"None"``, not an id."""
    if session_id is None:
        return None
    text = str(session_id).strip()
    if not text or text == "None":
        return None
    return text


def resolve_correlation(
    *,
    meta: dict[str, Any] | None,
    headers: dict[str, str] | None = None,
    session_id: str | None = None,
    session_chats: dict[str, str] | None = None,
    mint: Callable[[], str] | None = None,
) -> dict[str, Any]:
    """Resolve a chat_id without rewriting the caller's `_meta`.

    Priority: ``meta.chat_id`` → well-known headers → this MCP session's
    previously minted id → mint a new ``chat_*`` and remember it for the session.
    """
    meta = dict(meta or {})
    minted = mint or new_chat_id
    session_id = usable_session_id(session_id)
    if meta.get("chat_id"):
        chat_id = str(meta["chat_id"])
        source = "meta"
    else:
        header_id = chat_id_from_headers(headers)
        if header_id:
            chat_id = header_id
            source = "header"
        elif session_id and session_chats is not None and session_id in session_chats:
            chat_id = session_chats[session_id]
            source = "session"
        else:
            chat_id = minted()
            source = "minted"

    if session_id and session_chats is not None:
        session_chats.setdefault(session_id, chat_id)

    debug: dict[str, Any] = {
        "chat_id": chat_id,
        "chat_id_source": source,
    }
    if session_id:
        debug["session_id"] = session_id
    message_id = id_from_headers(headers, MESSAGE_ID_HEADER_KEYS)
    if message_id:
        debug["message_id"] = message_id
    if meta.get("call_id") is not None:
        debug["call_id"] = meta["call_id"]
        debug["call_id_source"] = "meta"
    else:
        debug["call_id"] = new_call_id()
        debug["call_id_source"] = "minted"
    if meta.get("trace_id") is not None:
        debug["trace_id"] = meta["trace_id"]
    if meta.get("source") is not None:
        debug["source"] = meta["source"]
    return debug


def record_call(
    *,
    tool: str,
    arguments: dict[str, Any],
    outcome: str,
    result: Any = None,
    error: str | None = None,
    meta: dict[str, Any] | None = None,
    debug: dict[str, Any] | None = None,
    duration_ms: float | None = None,
    event: str = EVENT_TOOLS_CALL,
) -> None:
    """Append one call record when MCP_TOOLCALL_LOG is set.

    `arguments` are the values received on `tools/call` before pydantic coercion.
    `outcome` is success, empty (valid call, no rows), or error.

    `meta` is whatever the caller put in the request's MCP `_meta` field (e.g.
    a chat-simulated caller's `call_id`/`chat_id`, or a caller talking to MCP
    directly passing its own correlation id). It is opaque to this function —
    logged verbatim when present — so a trace can be reconstructed from this
    JSONL file regardless of which path (chat-simulated or direct) made the
    call.

    `debug` is server-side correlation (resolved chat_id, source, session,
    result_n). It is *not* merged into `meta`, so existing exact-meta tests
    and callers keep a clean wire object.
    """
    log_path = os.environ.get("MCP_TOOLCALL_LOG")
    if not log_path:
        return
    row: dict[str, Any] = {
        "at": datetime.now(UTC).isoformat(),
        "event": event,
        "tool": tool,
        "arguments": arguments,
        "outcome": outcome,
    }
    if duration_ms is not None:
        row["duration_ms"] = duration_ms
    if meta:
        row["meta"] = meta
    debug_row = dict(debug) if debug else {}
    if outcome == OUTCOME_ERROR:
        row["error"] = error or "unknown error"
    else:
        row["result"] = result
        if isinstance(result, list):
            debug_row["result_n"] = len(result)
    if debug_row:
        row["debug"] = debug_row
        if debug_row.get("chat_id"):
            row["chat_id"] = debug_row["chat_id"]
    append_jsonl(log_path, row)

# --- server.py ---
"""FastMCP server exposing a small, deterministic real-estate-style mock API."""


import asyncio
import os
import time
from typing import Any

from fastmcp import FastMCP
from fastmcp.server.middleware import Middleware, MiddlewareContext



def _tool_delay_seconds() -> float:
    raw = os.environ.get("MCP_TOOL_DELAY_SECONDS", "0")
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 0.0


def _result_payload(result: Any) -> Any:
    structured = getattr(result, "structured_content", None)
    if isinstance(structured, dict) and "result" in structured:
        return structured["result"]
    if structured is not None:
        return structured
    content = getattr(result, "content", None)
    if not content:
        return []
    texts = [getattr(item, "text", None) for item in content]
    return texts[0] if len(texts) == 1 else texts


def _outcome_for_result(result: Any, payload: Any) -> str:
    if getattr(result, "is_error", False):
        return OUTCOME_ERROR
    if payload == [] or payload == {}:
        return OUTCOME_EMPTY
    return OUTCOME_SUCCESS


def _request_meta(context: MiddlewareContext) -> dict[str, Any]:
    """Pull the caller-supplied MCP `_meta` object off a tools/call request.

    Any client can attach arbitrary correlation data here (a chat-simulated
    caller's `call_id`/`chat_id`, or a direct caller's own trace id) — MCP
    reserves `_meta` exactly for this, so no protocol extension is needed.

    Note: `context.message.meta` is *not* the original request's `_meta` —
    FastMCP's own tools/call dispatch (fastmcp==3.4.7) rebuilds
    CallToolRequestParams internally and overwrites `_meta` with its own
    version-pinning metadata before middleware ever sees it. The original,
    client-supplied `_meta` survives on the lower-level request context
    instead, so that is what we read here.
    """
    ctx = context.fastmcp_context
    request_context = ctx.request_context if ctx is not None else None
    meta = getattr(request_context, "meta", None) if request_context is not None else None
    if meta is None:
        return {}
    if hasattr(meta, "model_dump"):
        meta = meta.model_dump(mode="json", exclude_none=True)
    return {k: v for k, v in dict(meta).items() if k != "progressToken"}


def _http_headers() -> dict[str, str]:
    """Best-effort request headers. Empty when this is not an HTTP hop."""
    try:
        from fastmcp.server.dependencies import get_http_headers
    except Exception:
        return {}
    try:
        return dict(get_http_headers() or {})
    except Exception:
        return {}


def _session_id(context: MiddlewareContext) -> str | None:
    ctx = context.fastmcp_context
    if ctx is None:
        return None
    try:
        raw = ctx.session_id
    except Exception:
        return None
    return usable_session_id(raw)


class ObservabilityMiddleware(Middleware):
    """Log every tools/call, including unknown names and validation failures.

    Also resolves a ``chat_id`` for debugging: caller `_meta`, then
    ``X-Chat-Id`` / ``X-Conversation-Id`` headers, then the id minted for
    this MCP session on the first call.
    """

    def __init__(self) -> None:
        super().__init__()
        self._session_chats: dict[str, str] = {}

    def _debug(self, context: MiddlewareContext, meta: dict[str, Any]) -> dict[str, Any]:
        return resolve_correlation(
            meta=meta,
            headers=_http_headers(),
            session_id=_session_id(context),
            session_chats=self._session_chats,
        )

    async def on_call_tool(self, context: MiddlewareContext, call_next):
        delay = _tool_delay_seconds()
        name = context.message.name
        arguments = dict(context.message.arguments or {})
        meta = _request_meta(context)
        debug = self._debug(context, meta)
        started = time.perf_counter()
        if delay:
            await asyncio.sleep(delay)
        try:
            result = await call_next(context)
        except Exception as exc:
            self._emit(name, arguments, meta, debug, started, outcome=OUTCOME_ERROR, error=str(exc))
            raise
        payload = _result_payload(result)
        outcome = _outcome_for_result(result, payload)
        if outcome == OUTCOME_ERROR:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, error=str(payload))
        else:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, result=payload)
        return result

    @staticmethod
    def _emit(
        name: str,
        arguments: dict[str, Any],
        meta: dict[str, Any],
        debug: dict[str, Any],
        started: float,
        *,
        outcome: str,
        result: Any = None,
        error: str | None = None,
    ) -> None:
        record_call(
            tool=name,
            arguments=arguments,
            outcome=outcome,
            result=result,
            error=error,
            meta=meta,
            debug=debug,
            duration_ms=round((time.perf_counter() - started) * 1000, 3),
        )


def create_mcp() -> FastMCP:
    """Build the Streamable HTTP mock server used by tests and Open WebUI."""
    mcp = FastMCP("mcp-toolcall-lab")
    mcp.add_middleware(ObservabilityMiddleware())

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_municipalities"])
    def find_municipalities(query: str) -> list[dict[str, str]]:
        return dispatch_tool("find_municipalities", {"query": query})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_transaction_prices"])
    def find_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
        return dispatch_tool("find_transaction_prices", {"municipality_code": municipality_code, "year": year})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_stations"])
    def find_stations(municipality_code: str) -> list[dict[str, str]]:
        return dispatch_tool("find_stations", {"municipality_code": municipality_code})

    @mcp.tool(description=TOOL_DESCRIPTIONS["fetch_wikipedia_section"])
    def fetch_wikipedia_section(title: str, heading: str = "") -> list[dict[str, str]]:
        return dispatch_tool("fetch_wikipedia_section", {"title": title, "heading": heading})

    return mcp


def run_server(mcp: FastMCP | None = None) -> None:
    server = mcp or create_mcp()
    server.run(
        transport="http",
        host=os.environ.get("MCP_HOST", "127.0.0.1"),
        port=int(os.environ.get("MCP_PORT", "8000")),
        path="/mcp",
    )


mcp = create_mcp()


if __name__ == "__main__":
    run_server(mcp)
