# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for Open WebUI tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python openwebui_mcp_mock.py

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
from __future__ import annotations

# --- catalog.py ---
"""Pure-Python mock data used by the FastMCP server and unit tests.

A valid call that matches nothing returns an empty list. That is not an error.
Protocol problems (unknown tool, invalid arguments, timeout) are errors.
"""


AVAILABLE_TOOLS = (
    "find_municipalities",
    "find_transaction_prices",
    "find_stations",
)

TOOL_DESCRIPTIONS = {
    "find_municipalities": "Find mock municipalities by name or prefecture.",
    "find_transaction_prices": "Return mock property transaction prices. This never calls a live API.",
    "find_stations": "Find mock stations in a municipality.",
}

MUNICIPALITIES = (
    {"code": "13101", "name": "Chiyoda", "prefecture": "Tokyo"},
    {"code": "14109", "name": "Yokohama", "prefecture": "Kanagawa"},
    {"code": "12207", "name": "Matsudo", "prefecture": "Chiba"},
)

STATIONS = {
    "14109": [{"name": "Yokohama", "line": "JR"}],
    "12207": [{"name": "Matsudo", "line": "JR Joban"}],
    "13101": [{"name": "Tokyo", "line": "JR"}],
}

KNOWN_MUNICIPALITY_CODES = tuple(row["code"] for row in MUNICIPALITIES)


def search_municipalities(query: str) -> list[dict[str, str]]:
    """Return deterministic municipality-like records; no external API is called."""
    normalized = query.strip().lower()
    if not normalized:
        return []
    return [
        row
        for row in MUNICIPALITIES
        if normalized in row["name"].lower() or normalized in row["prefecture"].lower()
    ]


def search_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
    """Return a stable fake transaction-price result, or [] when the code is unknown."""
    if municipality_code not in KNOWN_MUNICIPALITY_CODES:
        return []
    return [
        {
            "municipality_code": municipality_code,
            "year": year,
            "price_yen": 52_000_000,
            "property_type": "condominium",
            "source": "mock",
        }
    ]


def search_stations(municipality_code: str) -> list[dict[str, str]]:
    """Return deterministic station-like records, or [] when the code is unknown."""
    return list(STATIONS.get(municipality_code, []))

# --- record.py ---
"""JSONL call log shared by the package server and the generated standalone file."""


import json
import os
import time
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

OUTCOME_SUCCESS = "success"
OUTCOME_EMPTY = "empty"
OUTCOME_ERROR = "error"
EVENT_SCHEMA_VERSION = 2


def _normalized_meta(meta: dict[str, Any] | None) -> dict[str, Any]:
    """Normalize correlation without depending on another inline module."""
    raw = dict(meta or {})
    raw.pop("progressToken", None)
    raw.setdefault("trace_id", os.environ.get("MCP_TRACE_ID") or f"trace_{uuid.uuid4().hex[:24]}")
    raw.setdefault("request_id", os.environ.get("MCP_REQUEST_ID") or f"req_{uuid.uuid4().hex[:24]}")
    for key, env_name in (
        ("chat_id", "MCP_CHAT_ID"),
        ("conversation_id", "MCP_CONVERSATION_ID"),
    ):
        if not raw.get(key) and os.environ.get(env_name):
            raw[key] = os.environ[env_name]
    return raw


def record_call(
    *,
    tool: str,
    arguments: dict[str, Any],
    outcome: str,
    result: Any = None,
    error: str | None = None,
    meta: dict[str, Any] | None = None,
    duration_ms: float | None = None,
) -> None:
    """Append one versioned call record when MCP_TOOLCALL_LOG is set.

    Product chat ids are preserved only when supplied by a frontend/caller.
    A lab-owned trace_id and request_id are always present so anonymous calls
    are still debuggable and joinable.
    """
    log_path = os.environ.get("MCP_TOOLCALL_LOG")
    if not log_path:
        return
    event: dict[str, Any] = {
        "schema_version": EVENT_SCHEMA_VERSION,
        "event_id": f"evt_{uuid.uuid4().hex[:24]}",
        "at": datetime.now(UTC).isoformat(),
        "tool": tool,
        "arguments": arguments,
        "outcome": outcome,
        "meta": _normalized_meta(meta),
    }
    if duration_ms is not None:
        event["duration_ms"] = round(max(0.0, duration_ms), 3)
    if outcome == OUTCOME_ERROR:
        event["error"] = error or "unknown error"
    else:
        event["result"] = result
    path = Path(log_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as log_file:
        log_file.write(json.dumps(event, ensure_ascii=False, default=str) + "\n")

# --- server.py ---
"""FastMCP server exposing a small, deterministic real-estate-style mock API."""


import asyncio
import os
import time
from typing import Any

from fastmcp import FastMCP
from fastmcp.server.middleware import Middleware, MiddlewareContext



def _tool_delay_seconds() -> float:
    raw = os.environ.get("MCP_TOOL_DELAY_SECONDS", "0")
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 0.0


def _result_payload(result: Any) -> Any:
    structured = getattr(result, "structured_content", None)
    if isinstance(structured, dict) and "result" in structured:
        return structured["result"]
    if structured is not None:
        return structured
    content = getattr(result, "content", None)
    if not content:
        return []
    texts = [getattr(item, "text", None) for item in content]
    return texts[0] if len(texts) == 1 else texts


def _outcome_for_result(result: Any, payload: Any) -> str:
    if getattr(result, "is_error", False):
        return OUTCOME_ERROR
    if payload == [] or payload == {}:
        return OUTCOME_EMPTY
    return OUTCOME_SUCCESS


def _request_meta(context: MiddlewareContext) -> dict[str, Any]:
    """Pull the caller-supplied MCP `_meta` object off a tools/call request.

    Any client can attach arbitrary correlation data here (a chat-simulated
    caller's `call_id`/`chat_id`, or a direct caller's own trace id) — MCP
    reserves `_meta` exactly for this, so no protocol extension is needed.

    Note: `context.message.meta` is *not* the original request's `_meta` —
    FastMCP's own tools/call dispatch (fastmcp==3.4.7) rebuilds
    CallToolRequestParams internally and overwrites `_meta` with its own
    version-pinning metadata before middleware ever sees it. The original,
    client-supplied `_meta` survives on the lower-level request context
    instead, so that is what we read here.
    """
    ctx = context.fastmcp_context
    request_context = ctx.request_context if ctx is not None else None
    meta = getattr(request_context, "meta", None) if request_context is not None else None
    if meta is None:
        return {}
    if hasattr(meta, "model_dump"):
        meta = meta.model_dump(mode="json", exclude_none=True)
    return {k: v for k, v in dict(meta).items() if k != "progressToken"}


class ObservabilityMiddleware(Middleware):
    """Log every tools/call, including unknown names and validation failures."""

    async def on_call_tool(self, context: MiddlewareContext, call_next):
        delay = _tool_delay_seconds()
        if delay:
            await asyncio.sleep(delay)
        name = context.message.name
        arguments = dict(context.message.arguments or {})
        meta = _request_meta(context)
        started = time.perf_counter()
        try:
            result = await call_next(context)
        except Exception as exc:
            record_call(
                tool=name,
                arguments=arguments,
                outcome=OUTCOME_ERROR,
                error=str(exc),
                meta=meta,
                duration_ms=(time.perf_counter() - started) * 1000,
            )
            raise
        payload = _result_payload(result)
        outcome = _outcome_for_result(result, payload)
        if outcome == OUTCOME_ERROR:
            record_call(
                tool=name,
                arguments=arguments,
                outcome=outcome,
                error=str(payload),
                meta=meta,
                duration_ms=(time.perf_counter() - started) * 1000,
            )
        else:
            record_call(
                tool=name,
                arguments=arguments,
                outcome=outcome,
                result=payload,
                meta=meta,
                duration_ms=(time.perf_counter() - started) * 1000,
            )
        return result


def create_mcp() -> FastMCP:
    """Build the Streamable HTTP mock server used by tests and Open WebUI."""
    mcp = FastMCP("mcp-toolcall-lab")
    mcp.add_middleware(ObservabilityMiddleware())

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_municipalities"])
    def find_municipalities(query: str) -> list[dict[str, str]]:
        return search_municipalities(query)

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_transaction_prices"])
    def find_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
        return search_transaction_prices(municipality_code, year)

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_stations"])
    def find_stations(municipality_code: str) -> list[dict[str, str]]:
        return search_stations(municipality_code)

    return mcp


def run_server(mcp: FastMCP | None = None) -> None:
    server = mcp or create_mcp()
    server.run(
        transport="http",
        host=os.environ.get("MCP_HOST", "127.0.0.1"),
        port=int(os.environ.get("MCP_PORT", "8000")),
        path="/mcp",
    )


mcp = create_mcp()


if __name__ == "__main__":
    run_server(mcp)
