# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for Open WebUI tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python openwebui_mcp_mock.py

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
from __future__ import annotations

# --- mock/common.py ---
"""Stdlib bits both lab mocks can import without taking on each other's protocol.

Used by the MCP server (via ``record``) and the OpenAI-compatible demo.
No FastMCP, no OpenAI ``tool_calls`` decision, no MCP ``_meta`` schema —
those stay in the mock that owns that wire.
"""


import json
import uuid
from pathlib import Path
from typing import Any

CHAT_ID_HEADER_KEYS = (
    "x-chat-id",
    "x-lab-chat-id",
    "x-conversation-id",
    "x-owui-chat-id",
    "x-openwebui-chat-id",  # OWUI ENABLE_FORWARD_USER_INFO_HEADERS
)

MESSAGE_ID_HEADER_KEYS = (
    "x-openwebui-message-id",
    "x-message-id",
)


def new_chat_id() -> str:
    """Lab conversation pin. Not LibreChat's conversationId or OWUI chat.id."""
    return f"chat_{uuid.uuid4().hex[:24]}"


def new_call_id() -> str:
    """OpenAI ``tool_calls[].id`` shape. Same mint for MCP debug and the OpenAI mock."""
    return f"call_{uuid.uuid4().hex[:24]}"


def id_from_headers(headers: Any, keys: tuple[str, ...]) -> str | None:
    """Return the first non-empty value among ``keys`` (case-insensitive)."""
    if not headers:
        return None
    items = headers.items() if hasattr(headers, "items") else []
    lowered = {str(key).lower(): str(value).strip() for key, value in items}
    for key in keys:
        value = lowered.get(key)
        if value:
            return value
    return None


def chat_id_from_headers(headers: Any) -> str | None:
    return id_from_headers(headers, CHAT_ID_HEADER_KEYS)


def append_jsonl(path: str | Path, row: dict[str, Any]) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")


def read_jsonl(path: str | Path) -> list[dict[str, Any]]:
    """Read a JSONL file; skip blank or broken lines (debug logs are append-only)."""
    target = Path(path)
    if not target.is_file():
        return []
    events: list[dict[str, Any]] = []
    for line in target.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return events


def close_http11_sse(handler: Any) -> None:
    """End an HTTP/1.1 SSE response. Keep-alive with no length hangs the next request.

    Same class of bug as markdown ``demos/openai_compat_mock.py`` (c0dcd15).
    JSON responses that already send ``Content-Length`` do not need this.
    """
    handler.send_header("Connection", "close")
    handler.close_connection = True

# --- markdown_lib.py ---
"""Load the vendored stdlib ``markdown.py`` without making it a package import.

The sibling repo ships one file. We keep a snapshot under ``vendor/`` so
Docker / GitHub Pages builds stay offline after checkout. If the file is
missing, callers fall back to the stub's own ATX splitter.

Vendored ``markdown.py`` owns Markdown ↔ HTML/CSS and the thin Markdown ↔
Kramdown IAL subset. This module does **not** reimplement
``markdown_to_html``, ``html_to_markdown``, ``default_stylesheet``,
``markdown_to_kramdown``, or ``ial`` — callers use ``load_markdown()``.

``Section``/``slugify``/``parse_sections``/``lookup_heading`` live here
too: the heading -> body split is "use the vendored module, else a local
ATX regex fallback" regardless of *what* corpus is being split (a
fixtures/stub_front/*.md file for stub_front.py, or a live Wikipedia
extract converted to ATX for wikipedia_tool.py) -- one implementation,
not one per caller. Fuzzy heading lookup for the stub / Wikipedia tools
stays here; it is not the library's ``extract_section``.
"""


import hashlib
import importlib.util
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

def _repo_root() -> Path:
    """``src/mcp_toolcall_lab/markdown_lib.py`` -> repo root, two levels up.

    This module is also concatenated into the standalone
    ``openwebui_mcp_mock.py`` / ``librechat_mcp_mock.py`` (see
    ``export.py``'s ``INLINE_MODULES``), which run from a flat ``/app/``
    with no such ancestry -- ``.parents[2]`` would raise ``IndexError``
    there. Fall back to the file's own directory; ``markdown_py_path()``
    already has an explicit ``/app/vendor/markdown.py`` candidate for
    that case.
    """
    here = Path(__file__).resolve()
    parents = here.parents
    return parents[2] if len(parents) > 2 else here.parent


REPO_ROOT = _repo_root()
PROVENANCE_PATH = REPO_ROOT / "vendor" / "markdown.provenance.json"

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*#*\s*$")


@dataclass(frozen=True)
class Section:
    level: int
    title: str
    slug: str
    body: str
    line: int


def slugify(title: str) -> str:
    lowered = title.casefold().strip()
    return re.sub(r"[^a-z0-9]+", "-", lowered).strip("-")


def parse_sections(markdown: str) -> list[Section]:
    """Heading → body. Prefer vendored ``markdown.py``; ATX regex is the fallback.

    A section's body runs up to the next heading whose level is <= its own,
    so nested child headings (e.g. an H2 with H3 subsections) stay inside
    their parent's body instead of being cut off by the first child heading.
    This matches the Pages ``#wiki`` JS (``parseWikiSections`` / #33) and
    vendor ``markdown.py``'s own ``extract_section`` -- one inclusive
    contract for every corpus this splits (stub_front fixtures, Wikipedia
    extracts), on both the vendored and the fallback path.
    """
    md = load_markdown()
    if md is not None and hasattr(md, "split_sections"):
        parts = list(md.split_sections(markdown))
        levels = [int(part.get("level") or 0) for part in parts]
        titles = [str(part.get("title") or "") for part in parts]
        raws = [str(part.get("content") or "") for part in parts]

        starts: list[int] = []
        line = 1
        for raw in raws:
            starts.append(line)
            line += raw.count("\n") or 1

        sections: list[Section] = []
        for idx, (level, title) in enumerate(zip(levels, titles)):
            if level <= 0 or not title:
                continue
            end = idx + 1
            while end < len(parts) and not (levels[end] > 0 and levels[end] <= level):
                end += 1
            body_lines = "".join(raws[idx:end]).splitlines()
            body = "\n".join(body_lines[1:]).strip()
            sections.append(Section(level, title, slugify(title), body, starts[idx]))
        return sections
    lines = markdown.splitlines()
    found: list[tuple[int, int, str]] = []
    for index, line in enumerate(lines):
        match = _HEADING_RE.match(line)
        if match:
            found.append((index, len(match.group(1)), match.group(2).strip()))
    sections = []
    for idx, (start, level, title) in enumerate(found):
        end = len(lines)
        for j in range(idx + 1, len(found)):
            if found[j][1] <= level:
                end = found[j][0]
                break
        body = "\n".join(lines[start + 1 : end]).strip()
        sections.append(Section(level, title, slugify(title), body, start + 1))
    return sections


def lookup_heading(query: str, sections: list[Section], *, fuzzy: bool = True) -> Section | None:
    needle = query.strip()
    if needle.startswith("#"):
        needle = needle.lstrip("#").strip()
    if not needle:
        return None
    slug = slugify(needle)
    folded = needle.casefold()
    for section in sections:
        if section.title == needle or section.title.casefold() == folded or section.slug == slug:
            return section
    if not fuzzy:
        return None
    for section in sections:
        title = section.title.casefold()
        if title.startswith(folded) or folded.startswith(title) or folded in title:
            return section
    return None


def markdown_py_path() -> Path | None:
    override = os.environ.get("MARKDOWN_PY")
    candidates = []
    if override:
        candidates.append(Path(override))
    candidates.append(REPO_ROOT / "vendor" / "markdown.py")
    candidates.append(Path("/app/vendor/markdown.py"))
    for path in candidates:
        if path.is_file():
            return path
    return None


def load_markdown() -> ModuleType | None:
    path = markdown_py_path()
    if path is None:
        return None
    spec = importlib.util.spec_from_file_location("lab_vendored_markdown", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolves postponed annotations through sys.modules while
    # decorating classes. Register dynamic modules before exec_module(), just
    # like the normal import machinery does.
    previous = sys.modules.get(spec.name)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        if previous is None:
            sys.modules.pop(spec.name, None)
        else:
            sys.modules[spec.name] = previous
        raise
    return module


def git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def load_provenance() -> dict[str, str]:
    return json.loads(PROVENANCE_PATH.read_text(encoding="utf-8"))


def assert_markdown_provenance(path: Path | None = None) -> dict[str, str]:
    """Fail if the vendored file drifted from the recorded commit/blob."""
    recorded = load_provenance()
    target = path or markdown_py_path()
    if target is None:
        raise FileNotFoundError("vendor/markdown.py is missing")
    digest = hashlib.sha256(target.read_bytes()).hexdigest()
    blob = git_blob_sha(target)
    if blob != recorded["blob_sha"] or digest != recorded["sha256"]:
        raise ValueError(
            f"vendored markdown.py does not match {PROVENANCE_PATH.name}: "
            f"blob={blob} sha256={digest} recorded={recorded}"
        )
    return recorded


def ascii_artist_py_path() -> Path | None:
    """Locate the optional stdlib ascii_artist presentation adapter."""
    candidates = [REPO_ROOT / "vendor" / "ascii_artist.py", Path("/app/vendor/ascii_artist.py")]
    return next((path for path in candidates if path.is_file()), None)


def load_ascii_artist() -> ModuleType | None:
    """Load vendored ascii_artist.py; article parsing never depends on it."""
    path = ascii_artist_py_path()
    if path is None:
        return None
    spec = importlib.util.spec_from_file_location("lab_vendored_ascii_artist", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    previous = sys.modules.get(spec.name)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        if previous is None:
            sys.modules.pop(spec.name, None)
        else:
            sys.modules[spec.name] = previous
        raise
    return module


def to_web_ui_v1_html(text: str, *, title: str = "MCP article") -> str:
    """Emit web-ui v1 HTML via ascii_artist when available, safe pre fallback otherwise."""
    artist = load_ascii_artist()
    if artist is not None and hasattr(artist, "to_web_ui_v1_html"):
        try:
            return str(artist.to_web_ui_v1_html(text, title=title))
        except TypeError:
            return str(artist.to_web_ui_v1_html(text))
    import html as _html
    return (
        '<main class="ui-page" data-ui-theme="modern">'
        f'<section class="ui-panel"><h1 class="ui-title">{_html.escape(title)}</h1>'
        f'<pre class="ui-output">{_html.escape(text)}</pre></section></main>'
    )

# --- wikipedia_tool.py ---
"""Fetch a real Wikipedia article's plaintext extract over HTTP.

This is the one tool family in this lab's MCP catalog that is **not** a
deterministic offline mock -- every other tool in ``catalog.py`` returns
canned data on purpose (see its own module docstring: "never calls a
live API"). These helpers call Wikipedia's own action API for real, so a
title → full article → heading-pulldown → section-body UX can be tried
against a genuine article, not only the vendored ``fixtures/stub_front/*.md``
corpus.

Wikipedia's ``action=query&prop=extracts&explaintext=1&exsectionformat=wiki``
does the heavy lifting: it returns already-plain-text article content
(infoboxes, references, navboxes, and other markup already stripped by
Wikipedia's own extract engine) with MediaWiki ``== Heading ==`` markers.
No HTML scraping happens here, and ``markdown.py`` is never asked to
re-convert Wikipedia HTML -- those limits stay visible. The markers are
rewritten to ATX (``## Heading``) only to build a heading list / section
split via ``mcp_toolcall_lab.markdown_lib.parse_sections()``, the same
heading-splitter every other corpus in this repo already goes through.

The MCP server process keeps a small thread-safe TTL/LRU cache of
extracts keyed by language + title. Heading switches for the same
article reuse that entry. A MediaWiki redirect stores the requested
title and the canonical title on the same entry.

This sandbox's own dev environment cannot reach en.wikipedia.org (the
agent proxy denies the CONNECT, same as huggingface.co -- see
scripts/fetch_tiny_cpu_gguf.py's module docstring for that precedent),
so the live path is covered by unit tests against a mocked
``urllib.request.urlopen`` here, plus a JSON fixture file
(``MCP_TOOLCALL_LAB_WIKIPEDIA_FIXTURE``) for deterministic CI, plus one
real-network integration test gated behind
``MCP_TOOLCALL_LAB_LIVE_WIKIPEDIA=1`` -- never on by default, so a plain
``pytest -q`` never depends on Wikipedia being reachable.
"""


import json
import os
import re
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Literal


WIKIPEDIA_API = "https://{lang}.wikipedia.org/w/api.php"
DEFAULT_LANG = "en"
TIMEOUT = 10.0
USER_AGENT = "mcp-toolcall-lab/1.0 (https://github.com/myon-bioinformatics/mcp-toolcall-lab; lab demo, not production traffic)"
FIXTURE_ENV = "MCP_TOOLCALL_LAB_WIKIPEDIA_FIXTURE"
CACHE_TTL_SECONDS = 300.0
CACHE_MAXSIZE = 16
CACHE_TTL_ENV = "MCP_TOOLCALL_LAB_WIKI_CACHE_TTL"
CACHE_MAXSIZE_ENV = "MCP_TOOLCALL_LAB_WIKI_CACHE_MAXSIZE"

_WIKI_HEADING_RE = re.compile(r"^(=+)\s*(.+?)\s*=+\s*$", re.MULTILINE)

CacheLookup = Literal["hit", "miss"]


class WikipediaFetchError(RuntimeError):
    """The live fetch failed: network, timeout, no such article, or a bad response."""


def _norm_title(title: str) -> str:
    return title.strip().casefold()


def _env_float(name: str, default: float) -> float:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return max(0.0, float(raw))
    except ValueError:
        return default


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return max(1, int(raw))
    except ValueError:
        return default


@dataclass(frozen=True)
class WikipediaArticle:
    """One MediaWiki plaintext extract plus the heading list derived from it."""

    canonical_title: str
    lang: str
    extract: str

    def sections(self) -> list[Section]:
        atx = f"# {self.canonical_title}\n\n{_wiki_headings_to_atx(self.extract)}"
        return parse_sections(atx)

    def headings(self) -> list[dict[str, Any]]:
        return [{"heading": section.title, "level": section.level} for section in self.sections()]

    def as_tool_result(self) -> dict[str, Any]:
        return {
            "canonical_title": self.canonical_title,
            "lang": self.lang,
            "extract": self.extract,
            "headings": self.headings(),
        }


@dataclass
class _CacheEntry:
    article: WikipediaArticle
    expires_at: float
    aliases: set[tuple[str, str]]


class WikipediaExtractCache:
    """Thread-safe bounded TTL/LRU cache of Wikipedia extracts.

    Size is the number of canonical articles, not the number of title
    aliases. A redirect adds the requested title onto the canonical
    entry instead of allocating a second slot.

    ``get_or_load`` never holds ``_lock`` while ``loader`` runs (that
    path is Wikipedia HTTP or fixture I/O). Same-key misses single-flight
    via ``_inflight``; a hit on a different warm key is not blocked by
    an in-flight miss. The stub's ``ThreadingHTTPServer`` depends on that.
    """

    def __init__(
        self,
        *,
        maxsize: int | None = None,
        ttl_seconds: float | None = None,
        monotonic: Callable[[], float] | None = None,
    ) -> None:
        self.maxsize = max(1, int(maxsize if maxsize is not None else _env_int(CACHE_MAXSIZE_ENV, CACHE_MAXSIZE)))
        self.ttl_seconds = float(
            ttl_seconds if ttl_seconds is not None else _env_float(CACHE_TTL_ENV, CACHE_TTL_SECONDS)
        )
        self._monotonic = monotonic or time.monotonic
        self._lock = threading.RLock()
        self._order: OrderedDict[tuple[str, str], _CacheEntry] = OrderedDict()
        self._alias: dict[tuple[str, str], tuple[str, str]] = {}
        self._inflight: dict[tuple[str, str], threading.Event] = {}
        self.hits = 0
        self.misses = 0

    def _key(self, title: str, lang: str) -> tuple[str, str]:
        return (lang.strip().casefold() or DEFAULT_LANG, _norm_title(title))

    def _purge_entry_unlocked(self, canonical_key: tuple[str, str]) -> None:
        entry = self._order.pop(canonical_key, None)
        if entry is None:
            return
        for alias in entry.aliases:
            if self._alias.get(alias) == canonical_key:
                del self._alias[alias]

    def _get_unlocked(self, title: str, lang: str) -> WikipediaArticle | None:
        key = self._key(title, lang)
        canonical_key = self._alias.get(key)
        if canonical_key is None:
            return None
        entry = self._order.get(canonical_key)
        if entry is None:
            self._alias.pop(key, None)
            return None
        if entry.expires_at <= self._monotonic():
            self._purge_entry_unlocked(canonical_key)
            return None
        self._order.move_to_end(canonical_key)
        return entry.article

    def _evict_if_needed_unlocked(self) -> None:
        while len(self._order) >= self.maxsize:
            oldest, _entry = self._order.popitem(last=False)
            for alias in _entry.aliases:
                if self._alias.get(alias) == oldest:
                    del self._alias[alias]

    def _put_unlocked(self, article: WikipediaArticle, aliases: Iterable[str]) -> WikipediaArticle:
        lang = article.lang
        canonical_key = self._key(article.canonical_title, lang)
        alias_keys = {canonical_key}
        for title in aliases:
            if title and title.strip():
                alias_keys.add(self._key(title, lang))

        existing_canonical = self._alias.get(canonical_key)
        if existing_canonical is not None:
            existing = self._order.get(existing_canonical)
            if existing is not None and existing.expires_at > self._monotonic():
                for alias in alias_keys:
                    existing.aliases.add(alias)
                    self._alias[alias] = existing_canonical
                self._order.move_to_end(existing_canonical)
                return existing.article
            if existing_canonical in self._order:
                self._purge_entry_unlocked(existing_canonical)

        self._evict_if_needed_unlocked()
        entry = _CacheEntry(
            article=article,
            expires_at=self._monotonic() + self.ttl_seconds,
            aliases=set(alias_keys),
        )
        self._order[canonical_key] = entry
        for alias in alias_keys:
            previous = self._alias.get(alias)
            if previous is not None and previous != canonical_key:
                prev_entry = self._order.get(previous)
                if prev_entry is not None:
                    prev_entry.aliases.discard(alias)
            self._alias[alias] = canonical_key
        return article

    def get(self, title: str, lang: str = DEFAULT_LANG) -> WikipediaArticle | None:
        with self._lock:
            return self._get_unlocked(title, lang)

    def put(self, article: WikipediaArticle, aliases: Iterable[str] = ()) -> WikipediaArticle:
        with self._lock:
            return self._put_unlocked(article, aliases)

    def get_or_load(
        self,
        title: str,
        lang: str,
        loader: Callable[[str, str], tuple[WikipediaArticle, tuple[str, ...]]],
    ) -> tuple[WikipediaArticle, CacheLookup]:
        """Return a cached extract, loading on miss without holding the lock.

        Under the lock we only decide hit / join an in-flight miss / become
        the owner. ``loader`` (HTTP or fixture I/O) always runs outside it.
        Waiters re-check the cache after the owner finishes so a successful
        single-flight is one load; a failed load is not cached and waiters
        may become the next owner.
        """

        key = self._key(title, lang)
        while True:
            wait_for: threading.Event | None = None
            load_event: threading.Event | None = None
            with self._lock:
                cached = self._get_unlocked(title, lang)
                if cached is not None:
                    self.hits += 1
                    return cached, "hit"
                existing = self._inflight.get(key)
                if existing is not None:
                    wait_for = existing
                else:
                    load_event = threading.Event()
                    self._inflight[key] = load_event
                    self.misses += 1
            if wait_for is not None:
                wait_for.wait()
                continue
            assert load_event is not None
            try:
                article, extra_aliases = loader(title, lang)
            except BaseException:
                with self._lock:
                    if self._inflight.get(key) is load_event:
                        del self._inflight[key]
                raise
            else:
                with self._lock:
                    stored = self._put_unlocked(
                        article, (title, article.canonical_title, *extra_aliases)
                    )
                    if self._inflight.get(key) is load_event:
                        del self._inflight[key]
                    return stored, "miss"
            finally:
                load_event.set()

    def __len__(self) -> int:
        with self._lock:
            return len(self._order)

    def clear(self) -> None:
        with self._lock:
            self._order.clear()
            self._alias.clear()
            self.hits = 0
            self.misses = 0
            pending = list(self._inflight.values())
            self._inflight.clear()
        for event in pending:
            event.set()


_CACHE: WikipediaExtractCache | None = None
_CACHE_GUARD = threading.Lock()


def get_article_cache() -> WikipediaExtractCache:
    global _CACHE
    with _CACHE_GUARD:
        if _CACHE is None:
            _CACHE = WikipediaExtractCache()
        return _CACHE


def reset_article_cache(cache: WikipediaExtractCache | None = None) -> WikipediaExtractCache:
    """Replace the process-wide cache. Tests use this; production rarely needs it."""
    global _CACHE
    with _CACHE_GUARD:
        _CACHE = cache if cache is not None else WikipediaExtractCache()
        return _CACHE


def _wiki_headings_to_atx(text: str) -> str:
    """MediaWiki ``== Heading ==`` -> ATX ``## Heading``.

    Wikipedia's plaintext extract never emits a single ``=`` (that would be
    the article's own title, which is not part of the extract body), so
    level 2 is the shallowest marker actually seen; it is kept as ATX
    level 2 to match fixtures/stub_front/wiki_yokohama.md's own shape,
    where the fetched article's title is a separately-added level-1 ATX
    heading wrapping the lead paragraph and every ``==`` section under it.
    """

    def replace(match: re.Match[str]) -> str:
        level = len(match.group(1))
        return f"{'#' * level} {match.group(2)}"

    return _WIKI_HEADING_RE.sub(replace, text)


def _payload_covers_title(payload: dict[str, Any], title: str) -> bool:
    requested = _norm_title(title)
    if not requested:
        return False
    query = payload.get("query") or {}
    for page in (query.get("pages") or {}).values():
        if not isinstance(page, dict):
            continue
        if _norm_title(str(page.get("title") or "")) == requested:
            return True
    for redirect in query.get("redirects") or []:
        if not isinstance(redirect, dict):
            continue
        if _norm_title(str(redirect.get("from") or "")) == requested:
            return True
        if _norm_title(str(redirect.get("to") or "")) == requested:
            return True
    return False


def _redirect_aliases(payload: dict[str, Any]) -> tuple[str, ...]:
    aliases: list[str] = []
    for redirect in (payload.get("query") or {}).get("redirects") or []:
        if not isinstance(redirect, dict):
            continue
        source = str(redirect.get("from") or "").strip()
        if source:
            aliases.append(source)
    return tuple(aliases)


def _parse_extract_payload(payload: dict[str, Any], title: str, lang: str) -> tuple[str, str]:
    pages = (payload.get("query") or {}).get("pages") or {}
    page = next(iter(pages.values()), None)
    if not isinstance(page, dict) or "missing" in page:
        raise WikipediaFetchError(f"no {lang}.wikipedia.org article named {title!r}")
    extract = str(page.get("extract") or "")
    canonical_title = str(page.get("title") or title)
    return canonical_title, extract


def _read_fixture_payload(path: Path, title: str, lang: str) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise WikipediaFetchError(f"could not read wikipedia fixture {path}: {exc}") from exc
    if not isinstance(payload, dict) or not _payload_covers_title(payload, title):
        raise WikipediaFetchError(f"no {lang}.wikipedia.org article named {title!r}")
    return payload


def _fetch_extract_payload(title: str, lang: str) -> dict[str, Any]:
    fixture = os.environ.get(FIXTURE_ENV, "").strip()
    if fixture:
        return _read_fixture_payload(Path(fixture), title, lang)

    query = urllib.parse.urlencode(
        {
            "action": "query",
            "format": "json",
            "prop": "extracts",
            "explaintext": 1,
            "exsectionformat": "wiki",
            "redirects": 1,
            "titles": title,
        }
    )
    url = f"{WIKIPEDIA_API.format(lang=lang)}?{query}"
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
        raise WikipediaFetchError(f"could not fetch {title!r} from {lang}.wikipedia.org: {exc}") from exc
    if not isinstance(payload, dict):
        raise WikipediaFetchError(f"could not fetch {title!r} from {lang}.wikipedia.org: bad JSON")
    return payload


def _fetch_extract(title: str, lang: str) -> tuple[str, str]:
    """Return (canonical_title, plaintext_extract_with_wiki_headings)."""
    payload = _fetch_extract_payload(title, lang)
    return _parse_extract_payload(payload, title, lang)


def _load_uncached(title: str, lang: str) -> tuple[WikipediaArticle, tuple[str, ...]]:
    payload = _fetch_extract_payload(title, lang)
    canonical_title, extract = _parse_extract_payload(payload, title, lang)
    article = WikipediaArticle(canonical_title=canonical_title, lang=lang, extract=extract)
    return article, _redirect_aliases(payload)


def load_wikipedia_article(title: str, *, lang: str = DEFAULT_LANG) -> tuple[WikipediaArticle, CacheLookup]:
    """Return the article and whether the process cache already had it."""
    cleaned = title.strip()
    lang = (lang or DEFAULT_LANG).strip() or DEFAULT_LANG
    if not cleaned:
        raise WikipediaFetchError(f"no {lang}.wikipedia.org article named {title!r}")
    return get_article_cache().get_or_load(cleaned, lang, _load_uncached)


def fetch_article_sections(title: str, *, lang: str = DEFAULT_LANG) -> list[Section]:
    """Sections for a real Wikipedia article, via the same ``Section``
    shape (and the same ``parse_sections()``) as every other corpus in
    this repo -- so ``lookup_heading()`` works identically on either."""
    article, _lookup = load_wikipedia_article(title, lang=lang)
    return article.sections()


def fetch_wikipedia_article(title: str, *, lang: str = DEFAULT_LANG) -> dict[str, Any]:
    """MCP tool body: ``dispatch_tool("fetch_wikipedia_article", ...)``.

    One structured object: the MediaWiki plaintext extract as returned,
    the canonical title after redirects, and the heading list derived
    from that same extract. Heading switches must not require a second
    network fetch -- that is the process cache, not a second tool.
    """
    article, _lookup = load_wikipedia_article(title, lang=lang)
    return article.as_tool_result()


def fetch_wikipedia_section(title: str, heading: str = "", *, lang: str = DEFAULT_LANG) -> list[dict[str, Any]]:
    """MCP tool body: ``dispatch_tool("fetch_wikipedia_section", ...)``.

    No ``heading`` (or a blank one): return every section's title only --
    the "pulldown" list, deliberately without body text so a caller lists
    options before committing to a possibly-large fetch's body payload.
    A ``heading`` that matches (see ``lookup_heading()`` -- exact first,
    then fuzzy): that one section's title, its ATX form (``heading_markdown``,
    e.g. ``"## Geography"`` -- the section's own level, not hardcoded),
    and its body (everything after that heading up to the next one at a
    level <= its own, so nested child headings stay in the parent's body --
    same inclusive rule as every other ``Section`` in this repo, see
    ``markdown_lib.parse_sections()``). A ``heading`` that
    matches nothing is a normal empty result, not an error -- same
    "valid call, no rows" contract catalog.py's other tools use. A fetch
    that fails outright (network, no such article) raises
    ``WikipediaFetchError``, which the caller lets propagate as an actual
    MCP tool error, same as any other unexpected exception in this catalog.

    Compatibility: the list-of-rows shape is unchanged. The process cache
    means listing headings and then fetching one body is still one HTTP
    call for the same title+language.
    """
    article, _lookup = load_wikipedia_article(title, lang=lang)
    sections = article.sections()
    if not heading.strip():
        return [{"heading": section.title} for section in sections]
    match = lookup_heading(heading, sections, fuzzy=True)
    if match is None:
        return []
    heading_markdown = f"{'#' * match.level} {match.title}"
    return [{"heading": match.title, "heading_markdown": heading_markdown, "body": match.body}]

# --- pixiv_dictionary_tool.py ---
"""Low-impact pixiv Encyclopedia article adapter.

Fetches one public article HTML page, converts it with the vendored markdown.py,
then reuses the lab's common Markdown section model. A small TTL/LRU cache keeps
heading changes from causing repeat requests. Default CI must use fixtures.
"""

import os
import time
import urllib.parse
import urllib.request
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


PIXIV_ARTICLE = "https://dic.pixiv.net/a/{title}"
TIMEOUT = 10.0
USER_AGENT = "mcp-toolcall-lab/1.0 (+https://github.com/myon-bioinformatics/mcp-toolcall-lab; low-rate research adapter)"
FIXTURE_ENV = "MCP_TOOLCALL_LAB_PIXIV_FIXTURE"
CACHE_TTL_ENV = "MCP_TOOLCALL_LAB_PIXIV_CACHE_TTL"
CACHE_TTL_SECONDS = 600.0
CACHE_MAXSIZE = 8


class PixivDictionaryFetchError(RuntimeError):
    pass


@dataclass(frozen=True)
class PixivDictionaryArticle:
    canonical_title: str
    markdown: str
    source_url: str

    def sections(self) -> list[Section]:
        return parse_sections(self.markdown)

    def headings(self) -> list[dict[str, Any]]:
        return [{"heading": s.title, "level": s.level} for s in self.sections()]

    def as_tool_result(self) -> dict[str, Any]:
        return {
            "canonical_title": self.canonical_title,
            "markdown": self.markdown,
            "headings": self.headings(),
            "source_url": self.source_url,
        }


_CACHE: OrderedDict[str, tuple[float, PixivDictionaryArticle]] = OrderedDict()


def _ttl() -> float:
    try:
        return max(0.0, float(os.environ.get(CACHE_TTL_ENV, CACHE_TTL_SECONDS)))
    except ValueError:
        return CACHE_TTL_SECONDS


def reset_pixiv_dictionary_cache() -> None:
    _CACHE.clear()


def _article_html(title: str) -> tuple[str, str]:
    fixture = os.environ.get(FIXTURE_ENV, "").strip()
    url = PIXIV_ARTICLE.format(title=urllib.parse.quote(title.strip(), safe=""))
    if fixture:
        return Path(fixture).read_text(encoding="utf-8"), url
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "text/html"})
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
            charset = response.headers.get_content_charset() or "utf-8"
            return response.read().decode(charset, errors="replace"), url
    except Exception as exc:
        raise PixivDictionaryFetchError(f"could not fetch pixiv Encyclopedia article {title!r}: {exc}") from exc


def _html_to_markdown(raw_html: str) -> str:
    md = load_markdown()
    if md is None or not hasattr(md, "html_to_markdown"):
        raise PixivDictionaryFetchError("vendor/markdown.py with html_to_markdown() is required")
    converted = str(md.html_to_markdown(raw_html)).strip()
    if not converted:
        raise PixivDictionaryFetchError("pixiv Encyclopedia HTML produced no Markdown")
    return converted


def _canonical_title(markdown: str, requested: str) -> str:
    sections = parse_sections(markdown)
    for section in sections:
        if section.level == 1 and section.title.strip():
            return section.title.strip()
    return requested.strip()


def load_pixiv_dictionary_article(title: str) -> tuple[PixivDictionaryArticle, str]:
    cleaned = title.strip()
    if not cleaned:
        raise PixivDictionaryFetchError("article title is required")
    key = cleaned.casefold()
    now = time.monotonic()
    cached = _CACHE.get(key)
    if cached and cached[0] > now:
        _CACHE.move_to_end(key)
        return cached[1], "hit"
    raw_html, url = _article_html(cleaned)
    markdown = _html_to_markdown(raw_html)
    article = PixivDictionaryArticle(_canonical_title(markdown, cleaned), markdown, url)
    _CACHE[key] = (now + _ttl(), article)
    _CACHE.move_to_end(key)
    while len(_CACHE) > CACHE_MAXSIZE:
        _CACHE.popitem(last=False)
    return article, "miss"


def fetch_pixiv_dictionary_article(title: str) -> dict[str, Any]:
    article, cache = load_pixiv_dictionary_article(title)
    result = article.as_tool_result()
    result["cache"] = cache
    return result


def fetch_pixiv_dictionary_section(title: str, heading: str = "") -> list[dict[str, str]]:
    article, _ = load_pixiv_dictionary_article(title)
    sections = article.sections()
    if not heading.strip():
        return [{"heading": s.title, "level": str(s.level)} for s in sections]
    section = lookup_heading(heading, sections, fuzzy=True)
    if section is None:
        return []
    # parse_sections() may include nested descendants in a parent body. For a
    # selected heading, recover the exact heading from the normalized Markdown
    # and return only its own prose up to the next heading of any level.
    lines = article.markdown.splitlines()
    target = section.title.casefold()
    start = None
    for index, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            title_text = stripped.lstrip("#").strip().rstrip("#").strip()
            if title_text.casefold() == target:
                start = index + 1
                break
    if start is None:
        body = section.body
    else:
        own_body: list[str] = []
        for line in lines[start:]:
            if line.lstrip().startswith("#"):
                break
            own_body.append(line)
        body = "\n".join(own_body).strip()
    return [{"heading": section.title, "level": str(section.level), "body": body}]

# --- catalog.py ---
"""Pure-Python mock data used by the FastMCP server and unit tests.

A valid call that matches nothing returns an empty list. That is not an error.
Protocol problems (unknown tool, invalid arguments, timeout) are errors.

``fetch_wikipedia_section`` and ``fetch_wikipedia_article`` are the tools
below that are NOT deterministic offline mocks -- they are registered
here (same ``AVAILABLE_TOOLS``/``TOOL_DESCRIPTIONS``/``dispatch_tool()``
surface as every other tool, so they are callable the same way over real
MCP) but their actual implementation, including the "this makes a real
HTTP call" fact, lives in ``wikipedia_tool.py``, not here -- see that
module's docstring. The list-of-rows contract for
``fetch_wikipedia_section`` is unchanged.
"""


from typing import Any


AVAILABLE_TOOLS = (
    "find_municipalities",
    "find_transaction_prices",
    "find_stations",
    "fetch_wikipedia_section",
    "fetch_wikipedia_article",
    "fetch_pixiv_dictionary_section",
    "fetch_pixiv_dictionary_article",
)

TOOL_DESCRIPTIONS = {
    "find_municipalities": "Find mock municipalities by name or prefecture.",
    "find_transaction_prices": "Return mock property transaction prices. This never calls a live API.",
    "find_stations": "Find mock stations in a municipality.",
    "fetch_wikipedia_section": (
        "Fetch a real Wikipedia article's sections over HTTP (the one family here that is not a "
        "mock). Omit `heading` to list section titles (a pulldown); pass one to get that "
        "section's body. Unmatched heading is an empty result, not an error. Same article is "
        "cached in-process so heading switches do not refetch."
    ),
    "fetch_wikipedia_article": (
        "Fetch a real Wikipedia article as a MediaWiki plaintext extract (not HTML). Returns "
        "canonical_title, extract, and headings from that same fetch. In-process TTL/LRU cache "
        "reuses the extract when only the heading changes."
    ),
    "fetch_pixiv_dictionary_section": (
        "Fetch one public pixiv Encyclopedia article HTML page, normalize it through vendored "
        "markdown.py, and return its hierarchical heading list or one selected section. "
        "The cached article is reused when only the heading changes."
    ),
    "fetch_pixiv_dictionary_article": (
        "Fetch one public pixiv Encyclopedia article HTML page and normalize it through vendored "
        "markdown.py. Returns canonical_title, Markdown, hierarchical headings and source_url."
    ),
}

MUNICIPALITIES = (
    {"code": "13101", "name": "Chiyoda", "prefecture": "Tokyo"},
    {"code": "14109", "name": "Yokohama", "prefecture": "Kanagawa"},
    {"code": "12207", "name": "Matsudo", "prefecture": "Chiba"},
)

STATIONS = {
    "14109": [{"name": "Yokohama", "line": "JR"}],
    "12207": [{"name": "Matsudo", "line": "JR Joban"}],
    "13101": [{"name": "Tokyo", "line": "JR"}],
}

KNOWN_MUNICIPALITY_CODES = tuple(row["code"] for row in MUNICIPALITIES)


def search_municipalities(query: str) -> list[dict[str, str]]:
    """Return deterministic municipality-like records; no external API is called."""
    normalized = query.strip().lower()
    if not normalized:
        return []
    return [
        row
        for row in MUNICIPALITIES
        if normalized in row["name"].lower() or normalized in row["prefecture"].lower()
    ]


def search_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
    """Return a stable fake transaction-price result, or [] when the code is unknown."""
    if municipality_code not in KNOWN_MUNICIPALITY_CODES:
        return []
    return [
        {
            "municipality_code": municipality_code,
            "year": year,
            "price_yen": 52_000_000,
            "property_type": "condominium",
            "source": "mock",
        }
    ]


def search_stations(municipality_code: str) -> list[dict[str, str]]:
    """Return deterministic station-like records, or [] when the code is unknown."""
    return list(STATIONS.get(municipality_code, []))


def dispatch_tool(name: str, arguments: dict[str, Any]) -> Any:
    """In-process tool body. FastMCP wrappers and the stub front share this."""
    if name == "find_municipalities":
        return search_municipalities(str(arguments.get("query", "")))
    if name == "find_stations":
        return search_stations(str(arguments.get("municipality_code", "")))
    if name == "find_transaction_prices":
        return search_transaction_prices(
            str(arguments.get("municipality_code", "")),
            int(arguments.get("year", 2025)),
        )
    if name == "fetch_wikipedia_section":
        return fetch_wikipedia_section(
            str(arguments.get("title", "")),
            str(arguments.get("heading", "")),
            lang=str(arguments.get("lang") or DEFAULT_LANG),
        )
    if name == "fetch_wikipedia_article":
        return fetch_wikipedia_article(
            str(arguments.get("title", "")),
            lang=str(arguments.get("lang") or DEFAULT_LANG),
        )
    if name == "fetch_pixiv_dictionary_section":
        return fetch_pixiv_dictionary_section(
            str(arguments.get("title", "")),
            str(arguments.get("heading", "")),
        )
    if name == "fetch_pixiv_dictionary_article":
        return fetch_pixiv_dictionary_article(str(arguments.get("title", "")))
    raise KeyError(name)

# --- record.py ---
"""JSONL call log shared by the package server and the generated standalone file.

Id mints, header lookup, and the JSONL writer live in ``mock.common`` so the
OpenAI demo can use the same helpers without importing this MCP log schema.
"""


import os
from datetime import UTC, datetime
from typing import Any, Callable


OUTCOME_SUCCESS = "success"
OUTCOME_EMPTY = "empty"
OUTCOME_ERROR = "error"

# MCP JSON-RPC method names written as ``event``. Not a lab-specific protocol.
EVENT_INITIALIZE = "initialize"
EVENT_INITIALIZED = "notifications/initialized"
EVENT_TOOLS_LIST = "tools/list"
EVENT_TOOLS_CALL = "tools/call"
# Caller-side observation of a downstream Ironmate tools/call. Kept distinct
# so server-side tool-call counts do not double-count one logical execution.
EVENT_IRONMATE_CALLER = "ironmate-client/tools/call"

__all__ = [
    "CHAT_ID_HEADER_KEYS",
    "EVENT_INITIALIZE",
    "EVENT_INITIALIZED",
    "EVENT_IRONMATE_CALLER",
    "EVENT_TOOLS_CALL",
    "EVENT_TOOLS_LIST",
    "MESSAGE_ID_HEADER_KEYS",
    "OUTCOME_EMPTY",
    "OUTCOME_ERROR",
    "OUTCOME_SUCCESS",
    "chat_id_from_headers",
    "id_from_headers",
    "mcp_tool_calls",
    "new_call_id",
    "new_chat_id",
    "read_jsonl",
    "record_call",
    "record_protocol_event",
    "resolve_correlation",
    "usable_session_id",
]


def usable_session_id(session_id: object | None) -> str | None:
    """Keep a missing MCP session missing. ``str(None)`` is ``"None"``, not an id."""
    if session_id is None:
        return None
    text = str(session_id).strip()
    if not text or text == "None":
        return None
    return text


def resolve_correlation(
    *,
    meta: dict[str, Any] | None,
    headers: dict[str, str] | None = None,
    session_id: str | None = None,
    session_chats: dict[str, str] | None = None,
    mint: Callable[[], str] | None = None,
) -> dict[str, Any]:
    """Resolve a chat_id without rewriting the caller's `_meta`.

    Priority: ``meta.chat_id`` → well-known headers → this MCP session's
    previously minted id → mint a new ``chat_*`` and remember it for the session.
    """
    meta = dict(meta or {})
    minted = mint or new_chat_id
    session_id = usable_session_id(session_id)
    if meta.get("chat_id"):
        chat_id = str(meta["chat_id"])
        source = "meta"
    else:
        header_id = chat_id_from_headers(headers)
        if header_id:
            chat_id = header_id
            source = "header"
        elif session_id and session_chats is not None and session_id in session_chats:
            chat_id = session_chats[session_id]
            source = "session"
        else:
            chat_id = minted()
            source = "minted"

    if session_id and session_chats is not None:
        session_chats.setdefault(session_id, chat_id)

    debug: dict[str, Any] = {
        "chat_id": chat_id,
        "chat_id_source": source,
    }
    if session_id:
        debug["session_id"] = session_id
    message_id = id_from_headers(headers, MESSAGE_ID_HEADER_KEYS)
    if message_id:
        debug["message_id"] = message_id
    if meta.get("call_id") is not None:
        debug["call_id"] = meta["call_id"]
        debug["call_id_source"] = "meta"
    else:
        debug["call_id"] = new_call_id()
        debug["call_id_source"] = "minted"
    if meta.get("trace_id") is not None:
        debug["trace_id"] = meta["trace_id"]
    if meta.get("source") is not None:
        debug["source"] = meta["source"]
    return debug


def record_call(
    *,
    tool: str,
    arguments: dict[str, Any],
    outcome: str,
    result: Any = None,
    error: str | None = None,
    meta: dict[str, Any] | None = None,
    debug: dict[str, Any] | None = None,
    duration_ms: float | None = None,
    event: str = EVENT_TOOLS_CALL,
) -> None:
    """Append one call record when MCP_TOOLCALL_LOG is set.

    `arguments` are the values received on `tools/call` before pydantic coercion.
    `outcome` is success, empty (valid call, no rows), or error.

    `meta` is whatever the caller put in the request's MCP `_meta` field (e.g.
    a chat-simulated caller's `call_id`/`chat_id`, or a caller talking to MCP
    directly passing its own correlation id). It is opaque to this function —
    logged verbatim when present — so a trace can be reconstructed from this
    JSONL file regardless of which path (chat-simulated or direct) made the
    call.

    `debug` is server-side correlation (resolved chat_id, source, session,
    result_n). It is *not* merged into `meta`, so existing exact-meta tests
    and callers keep a clean wire object.
    """
    log_path = os.environ.get("MCP_TOOLCALL_LOG")
    if not log_path:
        return
    row: dict[str, Any] = {
        "at": datetime.now(UTC).isoformat(),
        "event": event,
        "tool": tool,
        "arguments": arguments,
        "outcome": outcome,
    }
    if duration_ms is not None:
        row["duration_ms"] = duration_ms
    if meta:
        row["meta"] = meta
    debug_row = dict(debug) if debug else {}
    if outcome == OUTCOME_ERROR:
        row["error"] = error or "unknown error"
    else:
        row["result"] = result
        if isinstance(result, list):
            debug_row["result_n"] = len(result)
    if debug_row:
        _attach_debug_ids(row, debug_row)
    append_jsonl(log_path, row)


def record_protocol_event(
    *,
    event: str,
    debug: dict[str, Any] | None = None,
) -> None:
    """Append one MCP JSON-RPC method row (initialize / tools/list / ...).

    Same JSONL as ``record_call``. ``event`` is the wire method name.
    """
    log_path = os.environ.get("MCP_TOOLCALL_LOG")
    if not log_path:
        return
    row: dict[str, Any] = {
        "at": datetime.now(UTC).isoformat(),
        "event": event,
    }
    debug_row = dict(debug) if debug else {}
    if debug_row:
        _attach_debug_ids(row, debug_row)
    append_jsonl(log_path, row)


def _attach_debug_ids(row: dict[str, Any], debug_row: dict[str, Any]) -> None:
    """Copy correlation ids onto the JSONL row. Message id is harvested, never minted."""
    row["debug"] = debug_row
    if debug_row.get("chat_id"):
        row["chat_id"] = debug_row["chat_id"]
    if debug_row.get("message_id"):
        row["message_id"] = debug_row["message_id"]


def mcp_tool_calls(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """``tools/call`` rows only. Handshake events are not tool executions."""
    return [
        event
        for event in events
        if event.get("event", EVENT_TOOLS_CALL) == EVENT_TOOLS_CALL and event.get("tool")
    ]

# --- server.py ---
"""FastMCP server exposing a small, deterministic real-estate-style mock API."""


import asyncio
import os
import sys
import time
from datetime import UTC, datetime
from typing import Any

from fastmcp import FastMCP
from fastmcp.server.middleware import Middleware, MiddlewareContext



def _tool_delay_seconds() -> float:
    raw = os.environ.get("MCP_TOOL_DELAY_SECONDS", "0")
    try:
        return max(0.0, float(raw))
    except ValueError:
        return 0.0


def _result_payload(result: Any) -> Any:
    structured = getattr(result, "structured_content", None)
    if isinstance(structured, dict) and "result" in structured:
        return structured["result"]
    if structured is not None:
        return structured
    content = getattr(result, "content", None)
    if not content:
        return []
    texts = [getattr(item, "text", None) for item in content]
    return texts[0] if len(texts) == 1 else texts


def _outcome_for_result(result: Any, payload: Any) -> str:
    if getattr(result, "is_error", False):
        return OUTCOME_ERROR
    if payload == [] or payload == {}:
        return OUTCOME_EMPTY
    return OUTCOME_SUCCESS


def _request_meta(context: MiddlewareContext) -> dict[str, Any]:
    """Pull the caller-supplied MCP `_meta` object off a tools/call request.

    Any client can attach arbitrary correlation data here (a chat-simulated
    caller's `call_id`/`chat_id`, or a direct caller's own trace id) — MCP
    reserves `_meta` exactly for this, so no protocol extension is needed.

    Note: `context.message.meta` is *not* the original request's `_meta` —
    FastMCP's own tools/call dispatch (fastmcp==3.4.7) rebuilds
    CallToolRequestParams internally and overwrites `_meta` with its own
    version-pinning metadata before middleware ever sees it. The original,
    client-supplied `_meta` survives on the lower-level request context
    instead, so that is what we read here.
    """
    ctx = context.fastmcp_context
    request_context = ctx.request_context if ctx is not None else None
    meta = getattr(request_context, "meta", None) if request_context is not None else None
    if meta is None:
        return {}
    if hasattr(meta, "model_dump"):
        meta = meta.model_dump(mode="json", exclude_none=True)
    return {k: v for k, v in dict(meta).items() if k != "progressToken"}


def _http_headers() -> dict[str, str]:
    """Best-effort request headers. Empty when this is not an HTTP hop."""
    try:
        from fastmcp.server.dependencies import get_http_headers
    except Exception:
        return {}
    try:
        return dict(get_http_headers() or {})
    except Exception:
        return {}


def _session_id(context: MiddlewareContext) -> str | None:
    ctx = context.fastmcp_context
    if ctx is None:
        return None
    try:
        raw = ctx.session_id
    except Exception:
        return None
    return usable_session_id(raw)


def _request_id(context: MiddlewareContext) -> str | None:
    """JSON-RPC / MCP request id. Missing stays missing."""
    ctx = context.fastmcp_context
    if ctx is None:
        return None
    try:
        raw = ctx.request_id
    except Exception:
        return None
    text = str(raw).strip()
    if not text or text == "None":
        return None
    return text


def _trace_stderr(message: str, *, level: str = "INFO") -> None:
    """Mirror JSONL protocol rows onto container stderr (time + level + text)."""
    stamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    print(f"{stamp} {level} {message}", file=sys.stderr, flush=True)


class ObservabilityMiddleware(Middleware):
    """Log every tools/call, including unknown names and validation failures.

    Also resolves a ``chat_id`` for debugging: caller `_meta`, then
    ``X-Chat-Id`` / ``X-Conversation-Id`` headers, then the id minted for
    this MCP session on the first call.

    ``initialize`` / ``notifications/initialized`` / ``tools/list`` are the
    same MCP methods on the wire, written to the same JSONL as ``event``.
    """

    def __init__(self) -> None:
        super().__init__()
        self._session_chats: dict[str, str] = {}

    def _debug(self, context: MiddlewareContext, meta: dict[str, Any]) -> dict[str, Any]:
        debug = resolve_correlation(
            meta=meta,
            headers=_http_headers(),
            session_id=_session_id(context),
            session_chats=self._session_chats,
        )
        request_id = _request_id(context)
        if request_id:
            debug["request_id"] = request_id
        return debug

    def _emit_protocol(self, event: str, context: MiddlewareContext) -> None:
        """Log the MCP method. Do not mint a lab ``chat_*`` on handshake."""
        debug: dict[str, Any] = {}
        session_id = _session_id(context)
        if session_id:
            debug["session_id"] = session_id
        request_id = _request_id(context)
        if request_id:
            debug["request_id"] = request_id
        headers = _http_headers()
        header_id = chat_id_from_headers(headers)
        if header_id:
            debug["chat_id"] = header_id
            debug["chat_id_source"] = "header"
        message_id = id_from_headers(headers, MESSAGE_ID_HEADER_KEYS)
        if message_id:
            debug["message_id"] = message_id
        record_protocol_event(event=event, debug=debug or None)
        _trace_stderr(
            f"event={event} session_id={debug.get('session_id') or '-'} "
            f"request_id={debug.get('request_id') or '-'} chat_id={debug.get('chat_id') or '-'} "
            f"message_id={debug.get('message_id') or '-'}"
        )

    async def on_initialize(self, context: MiddlewareContext, call_next):
        result = await call_next(context)
        self._emit_protocol(EVENT_INITIALIZE, context)
        return result

    async def on_list_tools(self, context: MiddlewareContext, call_next):
        result = await call_next(context)
        self._emit_protocol(EVENT_TOOLS_LIST, context)
        return result

    async def on_notification(self, context: MiddlewareContext, call_next):
        result = await call_next(context)
        method = context.method or ""
        if method == EVENT_INITIALIZED or method.endswith("initialized"):
            self._emit_protocol(EVENT_INITIALIZED, context)
        return result

    async def on_call_tool(self, context: MiddlewareContext, call_next):
        delay = _tool_delay_seconds()
        name = context.message.name
        arguments = dict(context.message.arguments or {})
        meta = _request_meta(context)
        debug = self._debug(context, meta)
        started = time.perf_counter()
        if delay:
            await asyncio.sleep(delay)
        try:
            result = await call_next(context)
        except Exception as exc:
            self._emit(name, arguments, meta, debug, started, outcome=OUTCOME_ERROR, error=str(exc))
            raise
        payload = _result_payload(result)
        outcome = _outcome_for_result(result, payload)
        if outcome == OUTCOME_ERROR:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, error=str(payload))
        else:
            self._emit(name, arguments, meta, debug, started, outcome=outcome, result=payload)
        return result

    @staticmethod
    def _emit(
        name: str,
        arguments: dict[str, Any],
        meta: dict[str, Any],
        debug: dict[str, Any],
        started: float,
        *,
        outcome: str,
        result: Any = None,
        error: str | None = None,
    ) -> None:
        record_call(
            tool=name,
            arguments=arguments,
            outcome=outcome,
            result=result,
            error=error,
            meta=meta,
            debug=debug,
            duration_ms=round((time.perf_counter() - started) * 1000, 3),
        )
        level = "ERROR" if outcome == OUTCOME_ERROR else "INFO"
        _trace_stderr(
            f"event={EVENT_TOOLS_CALL} tool={name} outcome={outcome} "
            f"session_id={debug.get('session_id') or '-'} "
            f"request_id={debug.get('request_id') or '-'} chat_id={debug.get('chat_id') or '-'} "
            f"message_id={debug.get('message_id') or '-'}",
            level=level,
        )


def create_mcp() -> FastMCP:
    """Build the Streamable HTTP mock server used by tests and Open WebUI."""
    mcp = FastMCP("mcp-toolcall-lab")
    mcp.add_middleware(ObservabilityMiddleware())

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_municipalities"])
    def find_municipalities(query: str) -> list[dict[str, str]]:
        return dispatch_tool("find_municipalities", {"query": query})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_transaction_prices"])
    def find_transaction_prices(municipality_code: str, year: int) -> list[dict[str, int | str]]:
        return dispatch_tool("find_transaction_prices", {"municipality_code": municipality_code, "year": year})

    @mcp.tool(description=TOOL_DESCRIPTIONS["find_stations"])
    def find_stations(municipality_code: str) -> list[dict[str, str]]:
        return dispatch_tool("find_stations", {"municipality_code": municipality_code})

    @mcp.tool(description=TOOL_DESCRIPTIONS["fetch_wikipedia_section"])
    def fetch_wikipedia_section(title: str, heading: str = "") -> list[dict[str, str]]:
        return dispatch_tool("fetch_wikipedia_section", {"title": title, "heading": heading})

    @mcp.tool(description=TOOL_DESCRIPTIONS["fetch_wikipedia_article"])
    def fetch_wikipedia_article(title: str, lang: str = "en") -> dict[str, Any]:
        return dispatch_tool("fetch_wikipedia_article", {"title": title, "lang": lang})

    @mcp.tool(description=TOOL_DESCRIPTIONS["fetch_pixiv_dictionary_section"])
    def fetch_pixiv_dictionary_section(title: str, heading: str = "") -> list[dict[str, str]]:
        return dispatch_tool("fetch_pixiv_dictionary_section", {"title": title, "heading": heading})

    @mcp.tool(description=TOOL_DESCRIPTIONS["fetch_pixiv_dictionary_article"])
    def fetch_pixiv_dictionary_article(title: str) -> dict[str, Any]:
        return dispatch_tool("fetch_pixiv_dictionary_article", {"title": title})

    return mcp


def run_server(mcp: FastMCP | None = None) -> None:
    server = mcp or create_mcp()
    server.run(
        transport="http",
        host=os.environ.get("MCP_HOST", "127.0.0.1"),
        port=int(os.environ.get("MCP_PORT", "8000")),
        path="/mcp",
    )


mcp = create_mcp()


if __name__ == "__main__":
    run_server(mcp)
