"""Emit copyable single-file MCP servers from the package source of truth.

The generated server is a plain FastMCP Streamable HTTP mock -- nothing in
it is Open WebUI- or LibreChat-specific, they're both clients speaking the
same protocol to the same tools. render()'s ``run_command``/``audience``
only change the file's own docstring (which file to copy, what to run) so
each product's README/docs can point at a same-named, same-purpose file
instead of one visibly branded for a different product. There is still
exactly one MCP mock implementation; this does not fork it.

``mock/common.py`` is the stdlib layer the OpenAI demo also imports (JSONL,
id mints, chat headers, SSE close). It is inlined here so the standalone
MCP file stays copy-pasteable. OpenAI ``tool_calls`` decision logic is
*not* inlined — that mock stays its own file.
"""

from __future__ import annotations

from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parents[1]
STANDALONE_PATH = REPO_ROOT / "openwebui_mcp_mock.py"
LIBRECHAT_STANDALONE_PATH = REPO_ROOT / "librechat_mcp_mock.py"
# Order matters: each module's own `from .x import ...` must already be
# defined by an earlier chunk once stripped. mock/common.py first for
# record.py; markdown_lib.py then wikipedia_tool.py before catalog.py
# (fetch_wikipedia_section's Section/lookup_heading/parse_sections).
INLINE_MODULES = ("mock/common.py", "markdown_lib.py", "wikipedia_tool.py", "pixiv_dictionary_tool.py", "catalog.py", "record.py", "server.py")


def _header(run_command: str, audience: str) -> str:
    return f'''\
# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for {audience} tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python {run_command}

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
'''


def _strip_relative_and_future(source: str) -> str:
    kept: list[str] = []
    skipping_paren_import = False
    for line in source.splitlines(keepends=True):
        stripped = line.lstrip()
        if skipping_paren_import:
            if ")" in stripped:
                skipping_paren_import = False
            continue
        if stripped.startswith("from __future__ import"):
            continue
        if stripped.startswith("from ."):
            if "(" in stripped and ")" not in stripped:
                skipping_paren_import = True
            continue
        kept.append(line)
    text = "".join(kept).strip()
    return text + "\n"


def render(*, run_command: str = "openwebui_mcp_mock.py", audience: str = "Open WebUI") -> str:
    """Return the standalone file contents generated from package modules."""
    chunks = [_header(run_command, audience), "from __future__ import annotations\n"]
    for filename in INLINE_MODULES:
        source = (PACKAGE_DIR / filename).read_text(encoding="utf-8")
        chunks.append(f"\n# --- {filename} ---\n")
        chunks.append(_strip_relative_and_future(source))
    return "".join(chunks)


def write_standalone(path: Path | None = None) -> Path:
    target = path or STANDALONE_PATH
    target.write_text(render(), encoding="utf-8")
    return target


def write_librechat_standalone(path: Path | None = None) -> Path:
    target = path or LIBRECHAT_STANDALONE_PATH
    target.write_text(
        render(run_command="librechat_mcp_mock.py", audience="LibreChat"), encoding="utf-8"
    )
    return target


def main() -> None:
    for path in (write_standalone(), write_librechat_standalone()):
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
