"""Emit a copyable single-file MCP server from the package source of truth."""

from __future__ import annotations

from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parents[1]
STANDALONE_PATH = REPO_ROOT / "openwebui_mcp_mock.py"
INLINE_MODULES = ("catalog.py", "record.py", "server.py")

HEADER = '''\
# Generated by: python -m mcp_toolcall_lab.export
# Do not edit by hand. Change src/mcp_toolcall_lab/ and regenerate.

"""Copy this entire file as a standalone mock MCP server for Open WebUI tests.

Requires Python 3.11+. Install once with: pip install "fastmcp==3.4.7"
Run with:                         python openwebui_mcp_mock.py

No API key or project-local imports are required. The default endpoint is
http://127.0.0.1:8000/mcp, using Streamable HTTP. Set MCP_HOST=0.0.0.0 when
another container or VM must connect.
"""
'''


def _strip_relative_and_future(source: str) -> str:
    kept: list[str] = []
    skipping_paren_import = False
    for line in source.splitlines(keepends=True):
        stripped = line.lstrip()
        if skipping_paren_import:
            if ")" in stripped:
                skipping_paren_import = False
            continue
        if stripped.startswith("from __future__ import"):
            continue
        if stripped.startswith("from ."):
            if "(" in stripped and ")" not in stripped:
                skipping_paren_import = True
            continue
        kept.append(line)
    text = "".join(kept).strip()
    return text + "\n"


def render() -> str:
    """Return the standalone file contents generated from package modules."""
    chunks = [HEADER, "from __future__ import annotations\n"]
    for filename in INLINE_MODULES:
        source = (PACKAGE_DIR / filename).read_text(encoding="utf-8")
        chunks.append(f"\n# --- {filename} ---\n")
        chunks.append(_strip_relative_and_future(source))
    return "".join(chunks)


def write_standalone(path: Path | None = None) -> Path:
    target = path or STANDALONE_PATH
    target.write_text(render(), encoding="utf-8")
    return target


def main() -> None:
    path = write_standalone()
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
